"""Tests for `PnlAttribution` long/typed DataFrame accessors.

Covers ``to_long_dataframe()``, ``to_carry_detail_dataframe()`` and
``to_credit_factor_dataframe()``.

The baseline `PnlAttribution` JSON shape is checked in under
`tests/fixtures/attribution_baseline.json` — it was generated by the Rust
helper at `finstack-quant/attribution/tests/attribution/dump_baseline.rs` (run with
``cargo test ... attribution::dump_baseline -- --nocapture --ignored``).
Detail blocks are injected via JSON patching so the tests stay self-contained
and don't require a full attribution pipeline.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pandas as pd
import pytest

from finstack_quant.attribution import PnlAttribution

BASELINE_PATH = Path(__file__).parent / "fixtures" / "attribution_baseline.json"


def _baseline_payload() -> dict[str, object]:
    return json.loads(BASELINE_PATH.read_text())


def _patch_attribution(**overrides: object) -> PnlAttribution:
    """Start from the canonical baseline and overlay select fields.

    Returns a freshly deserialized `PnlAttribution`.
    """
    payload = _baseline_payload()
    for key, value in overrides.items():
        payload[key] = copy.deepcopy(value)
    return PnlAttribution.from_json(json.dumps(payload))


def test_to_long_dataframe_is_empty_when_no_details() -> None:
    """No detail blocks populated → zero rows; schema columns must exist."""
    attr = PnlAttribution.from_json(json.dumps(_baseline_payload()))
    df = attr.to_long_dataframe()
    assert isinstance(df, pd.DataFrame)
    assert len(df) == 0


def test_to_long_dataframe_carries_rates_by_curve_and_totals() -> None:
    """Verify rates_detail.by_curve and discount/forward totals flow through.

    Note: rates_detail.by_tenor (and fx_detail.by_pair) use tuple-typed
    IndexMap keys which cannot be deserialized from JSON (serde_json rejects
    non-string keys). The DataFrame builder handles those rows correctly when
    they are present in an in-memory PnlAttribution — but they cannot be
    injected via from_json from Python, so this Python test only covers the
    JSON-roundtrippable shape (by_curve + totals). See the Rust-side
    `tests/attribution/credit_factor_waterfall_parallel.rs` for end-to-end
    coverage that does populate by_tenor via the attribution pipeline.
    """
    rates_detail = {
        "by_curve": {"USD-OIS": {"amount": "300", "currency": "USD"}},
        # by_tenor's tuple-keyed IndexMap rejects array form ([]) on
        # deserialization. Empty IndexMap serializes as an empty *map* {}.
        "by_tenor": {},
        "discount_total": {"amount": "300", "currency": "USD"},
        "forward_total": {"amount": "0", "currency": "USD"},
    }
    attr = _patch_attribution(
        rates_curves_pnl={"amount": "300", "currency": "USD"},
        rates_detail=rates_detail,
    )
    df = attr.to_long_dataframe()

    assert {"kind", "factor", "key_a", "key_b", "amount", "currency"} <= set(df.columns)

    by_curve = df[df["kind"] == "rates.by_curve"]
    assert len(by_curve) == 1
    assert by_curve.iloc[0]["key_a"] == "USD-OIS"
    assert by_curve.iloc[0]["amount"] == 300.0

    totals = df[df["kind"].isin(["rates.discount_total", "rates.forward_total"])]
    assert len(totals) == 2
    # Every rates row must carry the factor label "rates" and currency USD.
    assert (df[df["factor"] == "rates"]["currency"] == "USD").all()


def test_to_long_dataframe_carries_vol_by_surface() -> None:
    """String-keyed vol-surface IndexMap detail flows through cleanly."""
    vol_detail = {
        "by_surface": {"SPX-IVOL": {"amount": "42", "currency": "USD"}},
    }
    attr = _patch_attribution(
        vol_pnl={"amount": "42", "currency": "USD"},
        vol_detail=vol_detail,
    )
    df = attr.to_long_dataframe()

    vol_rows = df[df["factor"] == "vol"]
    assert len(vol_rows) == 1
    row = vol_rows.iloc[0]
    assert row["kind"] == "vol.by_surface"
    assert row["key_a"] == "SPX-IVOL"
    assert row["amount"] == pytest.approx(42.0)


def test_to_long_dataframe_carries_cross_factor_by_pair() -> None:
    """Cross-factor pairs are keyed by string labels.

    The Rust side uses ``"Rates×Credit"`` (U+00D7 MULTIPLICATION SIGN);
    Unicode escapes keep the source ASCII-clean while matching the wire.
    """
    cross_detail = {
        "total": {"amount": "10", "currency": "USD"},
        "by_pair": {
            "Rates×Credit": {"amount": "7", "currency": "USD"},
            "Spot×Vol": {"amount": "3", "currency": "USD"},
        },
    }
    attr = _patch_attribution(
        cross_factor_pnl={"amount": "10", "currency": "USD"},
        cross_factor_detail=cross_detail,
    )
    df = attr.to_long_dataframe()

    cross_rows = df[df["factor"] == "cross_factor"]
    assert len(cross_rows) == 2
    labels = set(cross_rows["key_a"])
    assert labels == {"Rates×Credit", "Spot×Vol"}


def test_to_carry_detail_dataframe_breakdown() -> None:
    """Carry detail with coupon_income + pull_to_par + roll_down + funding_cost.

    The typed accessor must return only ``carry.*`` rows.
    ``carry.theta`` is no longer emitted; the component lines partition ``total``.
    """
    carry_detail = {
        "total": {"amount": "15", "currency": "USD"},
        "coupon_income": {
            "total": {"amount": "12", "currency": "USD"},
        },
        "pull_to_par": {"amount": "2", "currency": "USD"},
        "roll_down": {
            "total": {"amount": "1", "currency": "USD"},
        },
        "funding_cost": {"amount": "0", "currency": "USD"},
    }
    attr = _patch_attribution(
        carry={"amount": "15", "currency": "USD"},
        carry_detail=carry_detail,
    )
    df = attr.to_carry_detail_dataframe()

    # Every row in the carry-detail DF must have factor == "carry".
    assert (df["factor"] == "carry").all()

    kinds = set(df["kind"])
    assert "carry.total" in kinds
    assert "carry.theta" not in kinds
    assert "carry.coupon_income" in kinds
    assert "carry.pull_to_par" in kinds
    assert "carry.roll_down" in kinds
    assert "carry.funding_cost" in kinds

    coupon_row = df[df["kind"] == "carry.coupon_income"].iloc[0]
    assert coupon_row["amount"] == 12.0

    # Component rows (coupon_income + pull_to_par + roll_down) partition carry.total.
    comps = df[df["kind"].isin({"carry.coupon_income", "carry.pull_to_par", "carry.roll_down"})]["amount"].sum()
    total = df[df["kind"] == "carry.total"]["amount"].iloc[0]
    assert abs(comps - total) < 1e-6


def test_to_credit_factor_dataframe_includes_generic_levels_adder_curve_shape() -> None:
    """Credit-factor detail with generic + 2 levels + adder + curve_shape.

    The typed accessor must surface all four kinds + the per-level rows.
    """
    credit_factor_detail = {
        "model_id": "test-model/abcdef0123456789",
        "generic_pnl": {"amount": "40", "currency": "USD"},
        "levels": [
            {
                "level_name": "rating",
                "total": {"amount": "30", "currency": "USD"},
                "by_bucket": {},
            },
            {
                "level_name": "region",
                "total": {"amount": "15", "currency": "USD"},
                "by_bucket": {},
            },
        ],
        "adder_pnl_total": {"amount": "10", "currency": "USD"},
        "curve_shape_pnl": {"amount": "5", "currency": "USD"},
        "adder_magnitude": {"amount": "10", "currency": "USD"},
    }
    attr = _patch_attribution(
        credit_curves_pnl={"amount": "100", "currency": "USD"},
        credit_factor_detail=credit_factor_detail,
    )
    df = attr.to_credit_factor_dataframe()

    assert (df["factor"] == "credit_factor").all()

    kinds = set(df["kind"])
    assert {
        "credit_factor.generic",
        "credit_factor.level",
        "credit_factor.adder",
        "credit_factor.curve_shape",
    } <= kinds

    levels = df[df["kind"] == "credit_factor.level"]
    assert len(levels) == 2
    level_names = set(levels["key_a"])
    assert level_names == {"rating", "region"}

    # Invariant: sum of all credit-factor components equals total credit P&L.
    generic = df[df["kind"] == "credit_factor.generic"]["amount"].sum()
    levels_sum = levels["amount"].sum()
    adder = df[df["kind"] == "credit_factor.adder"]["amount"].sum()
    curve_shape = df[df["kind"] == "credit_factor.curve_shape"]["amount"].sum()
    assert generic + levels_sum + adder + curve_shape == pytest.approx(100.0)


def test_to_credit_factor_dataframe_is_empty_when_no_credit_model() -> None:
    """The baseline carries no credit_factor_detail → empty DataFrame."""
    attr = PnlAttribution.from_json(json.dumps(_baseline_payload()))
    df = attr.to_credit_factor_dataframe()
    assert len(df) == 0


def test_to_long_dataframe_folds_in_carry_and_credit_factor_rows() -> None:
    """``to_long_dataframe()`` is a union of every detail breakdown.

    Must include the carry and credit-factor rows alongside the by-curve
    breakdowns. ``carry.theta`` is no longer emitted; roll_down absorbs any
    residual so the component rows still partition total.
    """
    carry_detail = {
        "total": {"amount": "10", "currency": "USD"},
        "roll_down": {
            "total": {"amount": "10", "currency": "USD"},
        },
    }
    credit_factor_detail = {
        "model_id": "test-model/aaaaaaaaaaaaaaaa",
        "generic_pnl": {"amount": "50", "currency": "USD"},
        "levels": [],
        "adder_pnl_total": {"amount": "0", "currency": "USD"},
        "curve_shape_pnl": {"amount": "0", "currency": "USD"},
    }
    attr = _patch_attribution(
        carry={"amount": "10", "currency": "USD"},
        carry_detail=carry_detail,
        credit_curves_pnl={"amount": "50", "currency": "USD"},
        credit_factor_detail=credit_factor_detail,
    )
    df = attr.to_long_dataframe()

    factors = set(df["factor"])
    assert "carry" in factors
    assert "credit_factor" in factors

    # theta must not appear; roll_down should partition total.
    carry_kinds = set(df[df["factor"] == "carry"]["kind"])
    assert "carry.theta" not in carry_kinds
    comps = df[df["kind"].isin({"carry.coupon_income", "carry.pull_to_par", "carry.roll_down"})]["amount"].sum()
    total = df[df["kind"] == "carry.total"]["amount"].iloc[0]
    assert abs(comps - total) < 1e-6
