//! Riemann-Liouville Volterra process increment generator.
//!
//! This module generates increments of the Riemann-Liouville (RL) Volterra
//! process that drives the variance in the rough Bergomi model of Bayer, Friz
//! & Gatheral (2016):
//!
//! ```text
//! Ỹ_t = √(2H) ∫₀ᵗ (t − s)^{H − ½} dW_s
//! ```
//!
//! # RL Volterra process vs. true fractional Brownian motion
//!
//! The RL Volterra process `Ỹ` must **not** be confused with true fractional
//! Brownian motion `B_H` (generated by [`CholeskyFbm`](super::fbm::CholeskyFbm)
//! and [`HybridFbm`](super::fbm::HybridFbm) via the Molchan-Golosov kernel).
//! Both share the marginal variance `t^{2H}`, but their autocovariance
//! structures differ:
//!
//! - `B_H` has **stationary** increments — `Cov(B_H(t+h)−B_H(t), …)` depends
//!   only on lags, not on `t`.
//! - `Ỹ` has **non-stationary** increments — the integral is truncated at the
//!   fixed origin `s = 0`, so the kernel seen from time `t` always references
//!   absolute time. `Ỹ` is the *truncated* Brownian semistationary process.
//!
//! The Bayer-Friz-Gatheral rBergomi model is defined with the RL Volterra
//! process, so this generator (not the true-fBM generators) is the correct
//! noise source for [`RoughBergomiProcess`](crate::process::rough_bergomi::RoughBergomiProcess).
//!
//! # Algorithm — the Bennedsen-Lunde-Pakkanen hybrid scheme
//!
//! [`RiemannLiouvilleVolterra`] uses the hybrid scheme of Bennedsen, Lunde &
//! Pakkanen (2017) with `κ = 1` near-field term — the standard choice for
//! rBergomi. With the RL power-law kernel `g(x) = x^γ`, `γ = H − ½ ∈ (−½, 0)`,
//! the discretized level on the uniform grid `t_k = k·Δt` is
//!
//! ```text
//! Ỹ_{t_k} = √(2H) · [ I_k + Σ_{j=0}^{k−2} g(b_{k−j}·Δt) · ΔW_j ]
//! ```
//!
//! where:
//!
//! - **Near-field (exact).** `I_k = ∫_{t_{k−1}}^{t_k} (t_k − s)^γ dW_s` is the
//!   *exact* Wiener integral over the last interval, where the kernel is
//!   singular at `s = t_k`. It is a Gaussian jointly distributed with the
//!   driving increment `ΔW_{k−1}`, with covariance matrix
//!
//!   ```text
//!   [ Δt                  Δt^{γ+1}/(γ+1)   ]
//!   [ Δt^{γ+1}/(γ+1)      Δt^{2γ+1}/(2γ+1) ]
//!   ```
//!
//! - **Far-field (power-law weighted Riemann sum).** For an interval at lag
//!   `m = k − j ≥ 2`, the kernel is approximated by the constant `g(b_m·Δt)`
//!   where `b_m` is the Bennedsen-Lunde-Pakkanen *optimal* evaluation point
//!   that minimises the L² approximation error:
//!
//!   ```text
//!   b_m = ( (m^{γ+1} − (m−1)^{γ+1}) / (γ+1) )^{1/γ} − m
//!   ```
//!
//! This yields an `O(n²)`-per-path generator that is far more accurate than a
//! plain forward Riemann sum, while being exact for the singular near-field.
//!
//! The `√(2H)` normalisation makes `Var(Ỹ_t) = 2H·∫₀ᵗ(t−s)^{2H−1}ds = t^{2H}`,
//! matching the rBergomi convexity correction `½η²t^{2H}`.
//!
//! # Noise layout
//!
//! Unlike the true-fBM generators, the hybrid scheme draws **two** independent
//! standard normals per step (so [`normals_per_step`] returns 2): one for the
//! driving Brownian increment `ΔW`, one for the exact near-field innovation.
//! The input `normals` slice is interleaved `[z_a₀, z_b₀, z_a₁, z_b₁, …]` and
//! must have length `num_steps · 2`.
//!
//! [`normals_per_step`]: super::fbm::FractionalNoiseGenerator::normals_per_step
//!
//! # References
//!
//! - Bennedsen, M., Lunde, A. & Pakkanen, M. S. (2017). Hybrid scheme for
//!   Brownian semistationary processes. *Finance and Stochastics*, 21(4),
//!   931–965.
//! - Bayer, C., Friz, P. & Gatheral, J. (2016). Pricing under rough
//!   volatility. *Quantitative Finance*, 16(6), 887–904.
//! - McCrickerd, R. & Pakkanen, M. S. (2018). Turbocharging Monte Carlo
//!   pricing for the rough Bergomi model. *Quantitative Finance*, 18(11),
//!   1877–1886.

use super::fbm::FractionalNoiseGenerator;
use finstack_core::math::fractional::HurstExponent;
use finstack_core::{Error, Result};

/// Riemann-Liouville Volterra process increment generator (κ = 1 hybrid scheme).
///
/// Produces the increments `ΔỸ_k = Ỹ_{t_{k+1}} − Ỹ_{t_k}` of the RL Volterra
/// process `Ỹ_t = √(2H)∫₀ᵗ(t−s)^{H−½}dW_s` on a **uniform** time grid. The
/// running sum `Σ_{k=0}^{m−1} ΔỸ_k` reconstructs the level `Ỹ_{t_m}`.
///
/// See the [module documentation](self) for the discretization scheme.
pub struct RiemannLiouvilleVolterra {
    /// Hurst exponent value H.
    hurst_val: f64,
    /// Number of time steps n.
    num_steps: usize,
    /// Uniform time step Δt.
    dt: f64,
    /// Normalisation constant √(2H).
    sqrt_two_h: f64,
    /// Lower-triangular Cholesky factor of the 2×2 near-field covariance
    /// matrix of `(ΔW, I)`: `[[l00, 0], [l10, l11]]`.
    l00: f64,
    l10: f64,
    l11: f64,
    /// Far-field power-law weights indexed by lag: `far_weight[m]` holds
    /// `g(b_{m}·Δt) = ((m + b_m)·Δt)^γ` for lag `m = 2, …, n`. Index 0 and 1
    /// are unused padding so that `far_weight[m]` is a direct lookup.
    far_weight: Vec<f64>,
}

impl RiemannLiouvilleVolterra {
    /// Create a new RL Volterra generator for a uniform grid.
    ///
    /// # Arguments
    ///
    /// * `t_end` — terminal time T > 0
    /// * `num_steps` — number of uniform steps n ≥ 1 (so `Δt = T / n`)
    /// * `hurst` — Hurst exponent H ∈ (0, 1)
    ///
    /// # Errors
    ///
    /// Returns [`Error::Validation`] if `t_end` is not finite and positive,
    /// `num_steps` is zero, or the Hurst exponent is outside (0, 1).
    pub fn new(t_end: f64, num_steps: usize, hurst: f64) -> Result<Self> {
        let h = HurstExponent::new(hurst)?;
        if !t_end.is_finite() || t_end <= 0.0 {
            return Err(Error::Validation(format!(
                "RiemannLiouvilleVolterra terminal time must be finite and positive, got {t_end}"
            )));
        }
        if num_steps == 0 {
            return Err(Error::Validation(
                "RiemannLiouvilleVolterra requires at least 1 time step".to_string(),
            ));
        }

        let h_val = h.value();
        let gamma = h_val - 0.5; // kernel exponent γ = H − ½ ∈ (−½, ½)
        let dt = t_end / num_steps as f64;
        let sqrt_two_h = (2.0 * h_val).sqrt();

        // 2×2 near-field covariance of (ΔW, I) where
        //   ΔW = ∫_{0}^{Δt} dW_s,  I = ∫_{0}^{Δt} u^γ dW_u  (lag u = t − s).
        //   Var(ΔW)  = Δt
        //   Cov(ΔW,I)= ∫_{0}^{Δt} u^γ du   = Δt^{γ+1}/(γ+1)
        //   Var(I)   = ∫_{0}^{Δt} u^{2γ} du = Δt^{2γ+1}/(2γ+1)
        let var_dw = dt;
        let cov = dt.powf(gamma + 1.0) / (gamma + 1.0);
        let var_i = dt.powf(2.0 * gamma + 1.0) / (2.0 * gamma + 1.0);

        // Lower Cholesky of [[var_dw, cov], [cov, var_i]].
        let l00 = var_dw.sqrt();
        let l10 = cov / l00;
        let schur = var_i - l10 * l10;
        // The 2×2 near-field covariance is positive-definite for γ ∈ (−½, ½)
        // in exact arithmetic; a tiny negative Schur complement is rounding
        // noise and is clamped. A materially negative value would indicate a
        // degenerate grid and is surfaced for visibility.
        if schur < -1e-12 * var_i.max(1.0) {
            tracing::warn!(
                schur,
                var_i,
                "RiemannLiouvilleVolterra: near-field Schur complement is significantly \
                 negative; the 2×2 covariance is ill-conditioned"
            );
        }
        let l11 = schur.max(0.0).sqrt();

        // Far-field weights g(b_m·Δt) = ((m + b_m)·Δt)^γ for lag m = 2..=n.
        //   b_m = ((m^{γ+1} − (m−1)^{γ+1})/(γ+1))^{1/γ} − m   (BLP optimal point)
        let mut far_weight = vec![0.0; num_steps + 1];
        for (m, w) in far_weight
            .iter_mut()
            .enumerate()
            .take(num_steps + 1)
            .skip(2)
        {
            let mf = m as f64;
            let raw = (mf.powf(gamma + 1.0) - (mf - 1.0).powf(gamma + 1.0)) / (gamma + 1.0);
            // raw > 0 for γ > −1; b_star ∈ (m−1, m) is the optimal point.
            let b_star = raw.powf(1.0 / gamma) - mf;
            *w = ((mf + b_star) * dt).powf(gamma);
        }

        Ok(Self {
            hurst_val: h_val,
            num_steps,
            dt,
            sqrt_two_h,
            l00,
            l10,
            l11,
            far_weight,
        })
    }

    /// Uniform time step Δt used by this generator.
    pub fn dt(&self) -> f64 {
        self.dt
    }

    /// Extract the per-step unit-variance driving Brownian normals `Z̃_k` from
    /// an interleaved `normals` input.
    ///
    /// The driving Brownian increment over step `k` is `ΔW̃_k = √Δt·Z̃_k`, and
    /// `Z̃_k` is exactly the first normal of each interleaved pair (the one
    /// scaled by `l00 = √Δt` to form `ΔW̃_k`). The rBergomi discretization
    /// correlates the spot Brownian motion against these normals.
    ///
    /// `normals` must have length `2·num_steps`; the returned vector has
    /// length `num_steps`.
    pub fn driving_normals(&self, normals: &[f64]) -> Vec<f64> {
        debug_assert_eq!(normals.len(), 2 * self.num_steps);
        (0..self.num_steps).map(|k| normals[2 * k]).collect()
    }

    /// Write the per-step driving Brownian normals into `out` (length
    /// `num_steps`). Allocation-free variant of [`driving_normals`].
    ///
    /// [`driving_normals`]: Self::driving_normals
    pub fn driving_normals_into(&self, normals: &[f64], out: &mut [f64]) {
        debug_assert_eq!(normals.len(), 2 * self.num_steps);
        debug_assert_eq!(out.len(), self.num_steps);
        for (k, o) in out.iter_mut().enumerate() {
            *o = normals[2 * k];
        }
    }
}

impl FractionalNoiseGenerator for RiemannLiouvilleVolterra {
    /// Transform `2·num_steps` i.i.d. normals into RL Volterra increments.
    ///
    /// `normals` is interleaved `[z_a₀, z_b₀, z_a₁, z_b₁, …]`. The pair
    /// `(z_a_k, z_b_k)` generates the driving Brownian increment `ΔW_k` and the
    /// exact near-field integral `I_{k+1}` for step `k`.
    fn generate(&self, normals: &[f64], out: &mut [f64]) {
        let n = self.num_steps;
        debug_assert_eq!(normals.len(), 2 * n);
        debug_assert_eq!(out.len(), n);

        // Decompose the interleaved input into the driving Brownian increments
        // ΔW_k and the exact near-field integrals I_{k+1}, using the 2×2
        // near-field Cholesky factor:
        //   ΔW_k     = l00 · z_a_k
        //   I_{k+1}  = l10 · z_a_k + l11 · z_b_k
        // dw[k] and near[k] both correspond to the interval [t_k, t_{k+1}].
        let mut dw = vec![0.0; n];
        let mut near = vec![0.0; n];
        for k in 0..n {
            let z_a = normals[2 * k];
            let z_b = normals[2 * k + 1];
            dw[k] = self.l00 * z_a;
            near[k] = self.l10 * z_a + self.l11 * z_b;
        }

        // Build the levels Ỹ_{t_k} for k = 1..=n, then emit increments.
        //   Ỹ_{t_k} = √(2H) · [ near[k−1] + Σ_{j=0}^{k−2} far_weight[k−j] · dw[j] ]
        // The far-field sum is accumulated incrementally: it is the discrete
        // convolution of the far-field kernel with the dw series.
        let mut prev_level = 0.0; // Ỹ_{t_0} = 0
        for k in 1..=n {
            // Far-field: Σ_{j=0}^{k−2} g(b_{k−j}·Δt) · ΔW_j.
            // lag m = k − j ranges over 2..=k as j ranges over 0..=k−2.
            let far_sum: f64 = dw[..k.saturating_sub(1)]
                .iter()
                .enumerate()
                .map(|(j, &dw_j)| self.far_weight[k - j] * dw_j)
                .sum();
            let level = self.sqrt_two_h * (near[k - 1] + far_sum);
            out[k - 1] = level - prev_level;
            prev_level = level;
        }
    }

    fn num_steps(&self) -> usize {
        self.num_steps
    }

    fn normals_per_step(&self) -> usize {
        2
    }

    fn hurst(&self) -> f64 {
        self.hurst_val
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Sum of the first `k` increments reconstructs the level `Ỹ_{t_k}`.
    fn level_at(out: &[f64], k: usize) -> f64 {
        out[..k].iter().sum()
    }

    // -- Construction ------------------------------------------------------

    #[test]
    fn rejects_bad_hurst() {
        assert!(RiemannLiouvilleVolterra::new(1.0, 10, 0.0).is_err());
        assert!(RiemannLiouvilleVolterra::new(1.0, 10, 1.0).is_err());
        assert!(RiemannLiouvilleVolterra::new(1.0, 10, -0.1).is_err());
        assert!(RiemannLiouvilleVolterra::new(1.0, 10, f64::NAN).is_err());
    }

    #[test]
    fn rejects_bad_grid() {
        assert!(RiemannLiouvilleVolterra::new(0.0, 10, 0.1).is_err());
        assert!(RiemannLiouvilleVolterra::new(-1.0, 10, 0.1).is_err());
        assert!(RiemannLiouvilleVolterra::new(f64::INFINITY, 10, 0.1).is_err());
        assert!(RiemannLiouvilleVolterra::new(1.0, 0, 0.1).is_err());
    }

    #[test]
    fn reports_two_normals_per_step() {
        let gen = RiemannLiouvilleVolterra::new(1.0, 32, 0.1).unwrap();
        assert_eq!(gen.normals_per_step(), 2);
        assert_eq!(gen.num_steps(), 32);
        assert!((gen.hurst() - 0.1).abs() < 1e-14);
    }

    // -- Kernel weights ----------------------------------------------------

    /// Unit test (i): the far-field power-law weight for lag `m` equals
    /// `((m + b_m)·Δt)^γ` with the Bennedsen-Lunde-Pakkanen optimal point
    /// `b_m`. Cross-checked against an explicit hand computation.
    #[test]
    fn far_field_weight_matches_blp_optimal_point() {
        let h = 0.1_f64;
        let gamma = h - 0.5; // = −0.4
        let n = 16;
        let t_end = 2.0;
        let dt = t_end / n as f64;
        let gen = RiemannLiouvilleVolterra::new(t_end, n, h).unwrap();

        for m in 2..=n {
            let mf = m as f64;
            // Hand-computed BLP optimal point b_m.
            let raw = (mf.powf(gamma + 1.0) - (mf - 1.0).powf(gamma + 1.0)) / (gamma + 1.0);
            let b_star = raw.powf(1.0 / gamma) - mf;
            let expected = ((mf + b_star) * dt).powf(gamma);
            assert!(
                (gen.far_weight[m] - expected).abs() < 1e-13,
                "lag {m}: weight {} != expected {expected}",
                gen.far_weight[m]
            );
            // The optimal point must lie strictly inside the interval (m−1, m).
            assert!(
                b_star > -1.0 && b_star < 0.0,
                "lag {m}: b_star {b_star} should place the eval point in (m−1, m)"
            );
        }
    }

    /// The exact near-field Cholesky factor reproduces the analytic 2×2
    /// covariance of `(ΔW, I)` on the singular last interval.
    #[test]
    fn near_field_covariance_is_exact() {
        let h = 0.15_f64;
        let gamma = h - 0.5;
        let n = 20;
        let t_end = 1.0;
        let dt = t_end / n as f64;
        let gen = RiemannLiouvilleVolterra::new(t_end, n, h).unwrap();

        // Reconstruct covariance from the Cholesky factor: C = L·Lᵀ.
        let var_dw = gen.l00 * gen.l00;
        let cov = gen.l00 * gen.l10;
        let var_i = gen.l10 * gen.l10 + gen.l11 * gen.l11;

        let expected_var_dw = dt;
        let expected_cov = dt.powf(gamma + 1.0) / (gamma + 1.0);
        let expected_var_i = dt.powf(2.0 * gamma + 1.0) / (2.0 * gamma + 1.0);

        assert!((var_dw - expected_var_dw).abs() < 1e-15);
        assert!((cov - expected_cov).abs() < 1e-14);
        assert!((var_i - expected_var_i).abs() < 1e-14);
    }

    // -- Variance reconstruction ------------------------------------------

    /// Unit test (ii): accumulating the generated-increment variance must
    /// reconstruct `Var(Ỹ_{t_k}) = t_k^{2H}` for the √(2H)-normalised process.
    ///
    /// `Var(Ỹ_{t_k})` is computed exactly from the linear map from the i.i.d.
    /// normals: with `Ỹ_{t_k} = Σ_i c_i Z_i`, `Var = Σ_i c_iᵀ` because the
    /// `Z_i` are independent. We obtain the coefficients `c_i` by feeding unit
    /// basis vectors through `generate`. The near-field interval is exact, so
    /// the only discretization error is the far-field power-law approximation
    /// (Bennedsen-Lunde-Pakkanen show it is high-order accurate).
    #[test]
    fn variance_reconstructs_t_pow_2h() {
        for &h in &[0.1_f64, 0.3, 0.45] {
            let n = 200;
            let t_end = 1.0;
            let gen = RiemannLiouvilleVolterra::new(t_end, n, h).unwrap();
            let dt = gen.dt();
            let num_normals = 2 * n;

            // Variance of Ỹ_{t_k} = sum over independent normals of (coeff)².
            // coeff_i for level k = Σ_{step<k} out[step] when normals = e_i.
            let mut var_at = vec![0.0; n + 1];
            for i in 0..num_normals {
                let mut normals = vec![0.0; num_normals];
                normals[i] = 1.0;
                let mut out = vec![0.0; n];
                gen.generate(&normals, &mut out);
                for (k, var_k) in var_at.iter_mut().enumerate().take(n + 1).skip(1) {
                    let c = level_at(&out, k);
                    *var_k += c * c;
                }
            }

            for (k, &var_k) in var_at.iter().enumerate().take(n + 1).skip(1) {
                let t_k = k as f64 * dt;
                let expected = t_k.powf(2.0 * h);
                let rel = (var_k - expected).abs() / expected;
                // 1% relative tolerance: the far-field power-law approximation
                // is the only source of error; the near-field is exact.
                assert!(
                    rel < 1e-2,
                    "H={h} k={k}: Var={var_k} expected t^2H={expected} rel_err={rel}"
                );
            }
        }
    }

    /// Unit test (iii): at H = 0.5 the RL kernel `(t−s)^0 = 1` makes `Ỹ`
    /// standard Brownian motion, so the increments must be i.i.d. `N(0, Δt)`.
    #[test]
    fn h_half_yields_standard_brownian_motion() {
        let n = 64;
        let t_end = 1.0;
        let gen = RiemannLiouvilleVolterra::new(t_end, n, 0.5).unwrap();
        let dt = gen.dt();
        let num_normals = 2 * n;

        // For BM the increment Δỹ_k must depend ONLY on the k-th step's
        // normals — feed e_i and confirm out[step] is nonzero only at the
        // matching step, with magnitude √Δt on the driving normal.
        for i in 0..num_normals {
            let mut normals = vec![0.0; num_normals];
            normals[i] = 1.0;
            let mut out = vec![0.0; n];
            gen.generate(&normals, &mut out);

            let step = i / 2;
            let is_driving = i % 2 == 0; // z_a drives ΔW
            for (s, &v) in out.iter().enumerate() {
                if s == step {
                    if is_driving {
                        // ΔW contribution: √(2H)·√Δt with H=0.5 ⇒ √Δt.
                        assert!(
                            (v - dt.sqrt()).abs() < 1e-12,
                            "H=0.5 step {s}: driving increment {v} != √Δt {}",
                            dt.sqrt()
                        );
                    } else {
                        // For γ=0 the near-field integral I equals ΔW exactly,
                        // so the near-field innovation z_b carries zero weight.
                        assert!(
                            v.abs() < 1e-12,
                            "H=0.5 step {s}: near-field innovation should vanish, got {v}"
                        );
                    }
                } else {
                    assert!(
                        v.abs() < 1e-12,
                        "H=0.5: increment {s} should not depend on step-{step} normal, got {v}"
                    );
                }
            }
        }
    }

    /// At H = 0.5 the per-step variance is exactly Δt and increments are
    /// uncorrelated — verified through the coefficient map.
    #[test]
    fn h_half_increment_variance_is_dt() {
        let n = 50;
        let t_end = 2.0;
        let gen = RiemannLiouvilleVolterra::new(t_end, n, 0.5).unwrap();
        let dt = gen.dt();
        let num_normals = 2 * n;

        let mut inc_var = vec![0.0; n];
        for i in 0..num_normals {
            let mut normals = vec![0.0; num_normals];
            normals[i] = 1.0;
            let mut out = vec![0.0; n];
            gen.generate(&normals, &mut out);
            for (s, &v) in out.iter().enumerate() {
                inc_var[s] += v * v;
            }
        }
        for (s, &var) in inc_var.iter().enumerate() {
            assert!(
                (var - dt).abs() < 1e-12,
                "H=0.5 increment {s}: variance {var} != Δt {dt}"
            );
        }
    }

    // -- Determinism -------------------------------------------------------

    #[test]
    fn generation_is_deterministic() {
        let gen = RiemannLiouvilleVolterra::new(1.5, 40, 0.12).unwrap();
        let normals: Vec<f64> = (0..80).map(|i| 0.1 * ((i as f64) - 40.0)).collect();
        let mut out_a = vec![0.0; 40];
        let mut out_b = vec![0.0; 40];
        gen.generate(&normals, &mut out_a);
        gen.generate(&normals, &mut out_b);
        for (a, b) in out_a.iter().zip(out_b.iter()) {
            assert_eq!(a.to_bits(), b.to_bits(), "generation must be bit-identical");
        }
    }

    #[test]
    fn level_zero_at_origin_and_finite() {
        let gen = RiemannLiouvilleVolterra::new(1.0, 30, 0.2).unwrap();
        let normals: Vec<f64> = (0..60).map(|i| 0.3 * (-1.0_f64).powi(i)).collect();
        let mut out = vec![0.0; 30];
        gen.generate(&normals, &mut out);
        assert!(out.iter().all(|x| x.is_finite()));
        // Ỹ_{t_0} = 0 by construction (sum of zero increments).
        assert_eq!(level_at(&out, 0), 0.0);
    }
}
