//! Euler discretization for the Cheyette + rough vol process.
//!
//! Advances the two-dimensional Markov state (x, y) of the Cheyette model
//! with stochastic volatility driven by a Riemann-Liouville Volterra process,
//! mirroring the rBergomi scheme in
//! [`rough_bergomi`](super::rough_bergomi).
//!
//! # Noise Layout
//!
//! The discretization expects `z` with three entries:
//!
//! - `z[0]` — independent standard normal for the uncorrelated rate component
//! - `z[1]` — increment `ΔỸ` of the Riemann-Liouville Volterra process for the
//!   current step, pre-generated by the engine's fractional noise integration
//!   from a [`RiemannLiouvilleVolterra`](crate::rng::volterra::RiemannLiouvilleVolterra)
//!   generator
//! - `z[2]` — the **unit-variance driving Brownian normal** `Z̃_k` for the
//!   current step, i.e. `ΔW̃_k / √dt`, where `W̃` is the Brownian motion that
//!   drives the Volterra process. Also supplied by the fractional noise
//!   integration.
//!
//! # Rate–Vol Correlation 
//!
//! The model correlates the rate Brownian motion `W` with the Volterra
//! *driver* `W̃` by `dW·dW̃ = ρ dt`. The correlated rate increment is built
//! directly from the driving normal `Z̃_k`:
//!
//! ```text
//! Z_corr = ρ Z̃ + √(1 − ρ²) Z_indep
//! dW_rate = Z_corr √dt
//! ```
//!
//! This is exact: `Z̃` is genuinely unit-variance (`ΔW̃_k = √dt · Z̃_k`) and
//! i.i.d. across steps, unlike the Volterra *increment* `ΔỸ`, whose variance
//! is neither `dt^{2H}` nor stationary and which is autocorrelated across
//! steps. The previous scheme rescaled `ΔỸ` by `dt^H`, leaving the rate
//! driver with non-Brownian (autocorrelated, wrong-variance) increments.
//!
//! # Euler Steps (left-point scheme)
//!
//! ```text
//! σ(t) = σ₀(t) · exp(½·η · Ỹ(t) − ¼ · η² · t^{2H})
//! x(t+dt) = x(t) + [y(t) − κ·x(t)] · dt + σ(t) · √dt · Z_corr
//! y(t+dt) = y(t) + [σ(t)² − 2κ·y(t)] · dt
//! ```
//!
//! The σ reconstruction uses rBergomi **variance-lognormal** semantics: the
//! variance `V(t) = σ(t)² = σ₀²·exp(η·Ỹ(t) − ½η²·t^{2H})` is lognormal with
//! full compensation, so `E[σ²(t)] = σ₀²(t)` (see the
//! [process module docs](super::super::process::cheyette_rough)).
//!
//! The volatility is evaluated at the **left endpoint**: `Ỹ(t)` is the
//! Volterra level accumulated strictly before this step, so `σ(t)` is
//! independent of the step's own shock `Z̃_k`. Evaluating σ at `t+dt`
//! (including this step's `ΔỸ`) would correlate the diffusion coefficient
//! with the step's own noise, creating a spurious `ρ`-proportional Itô
//! drift in x. The y update is deterministic given σ(t).
//!
//! # Work Buffer
//!
//! `work[0]` stores the running accumulated Riemann-Liouville Volterra
//! process `Ỹ(t) = √(2H)·∫₀ᵗ(t−s)^{H−½}dW̃_s` with `Var(Ỹ(t)) = t^{2H}`.
//! The engine must zero the work buffer before each new path (see
//! [`simulate_path_fractional`](crate::engine_fractional::simulate_path_fractional)).
//!
//! # References
//!
//! - Cheyette, O. (1994). "Markov Representation of the Heath-Jarrow-Morton
//!   Model." Working paper.
//! - Andersen, L. & Piterbarg, V. (2010). *Interest Rate Modeling*, Volume II,
//!   Chapter 12.
//! - Bayer, C., Friz, P. & Gatheral, J. (2016). "Pricing under rough
//!   volatility." *Quantitative Finance*, 16(6), 887–904.
//! - Bennedsen, M., Lunde, A. & Pakkanen, M. S. (2017). "Hybrid scheme for
//!   Brownian semistationary processes." *Finance and Stochastics*, 21(4),
//!   931–965.

use super::super::process::cheyette_rough::CheyetteRoughVolProcess;
use super::super::traits::Discretization;
use finstack_core::math::fractional::HurstExponent;

/// Euler discretization for the Cheyette + rough vol process.
///
/// This scheme reconstructs the stochastic volatility from the base vol curve
/// and the accumulated Riemann-Liouville Volterra path at the left endpoint of
/// each time step, then applies an Euler–Maruyama update to both the rate
/// state x and the deterministic variance accumulator y.
///
/// See the [module-level documentation](self) for details on noise layout,
/// correlation handling, and the work buffer.
#[derive(Debug, Clone)]
pub struct CheyetteRoughEuler {
    /// Hurst exponent of the Riemann-Liouville Volterra driver.
    hurst: HurstExponent,
}

impl CheyetteRoughEuler {
    /// Create a new Cheyette rough vol Euler discretization.
    ///
    /// # Arguments
    ///
    /// * `hurst` - Validated Hurst exponent, must match the process.
    pub fn new(hurst: HurstExponent) -> Self {
        Self { hurst }
    }

    /// Return the stored Hurst exponent.
    pub fn hurst(&self) -> HurstExponent {
        self.hurst
    }
}

impl Discretization<CheyetteRoughVolProcess> for CheyetteRoughEuler {
    fn step(
        &self,
        process: &CheyetteRoughVolProcess,
        t: f64,
        dt: f64,
        x: &mut [f64],
        z: &[f64],
        work: &mut [f64],
    ) {
        let p = process.params();
        let h = p.hurst.value();
        let eta = p.eta;
        let rho = p.rho;

        let z_indep = z[0]; // Independent standard normal
        let d_y = z[1]; // RL Volterra increment ΔỸ for this step (pre-generated)
        let z_drive = z[2]; // Unit-variance driving Brownian normal Z̃ = ΔW̃/√dt

        // Reconstruct the LEFT-endpoint volatility from the Volterra level
        // accumulated *up to* time t (work[0] = Ỹ_t, before this step's ΔỸ),
        // using rBergomi variance-lognormal semantics (E[σ²(t)] = σ₀²(t)):
        //   σ(t) = σ₀(t) · exp(½ η Ỹ_t − ¼ η² t^{2H})
        //
        // The left endpoint is essential : σ(t) is built
        // from driving normals strictly before this step, so it is
        // independent of this step's shock Z̃_k. Using the end-of-step σ(t+dt)
        // (which depends on ΔỸ_k, hence on Z̃_k) would correlate the diffusion
        // coefficient with the step's own noise and add a spurious
        // ρ-proportional drift to x.
        let two_h = 2.0 * h;
        let y_t = work[0];
        let sigma_base = p.sigma_base_value(t);
        let exponent = 0.5 * eta * y_t - 0.25 * eta * eta * t.powf(two_h);
        let sigma_t = (sigma_base * exponent.exp()).max(0.0);

        // Correlate the rate noise with the Volterra driver: dW·dW̃ = ρ dt,
        // so the correlated rate normal is built from the
        // unit-variance driving normal Z̃ — exact, with no dt^H rescaling.
        let z_correlated = rho * z_drive + (1.0 - rho * rho).max(0.0).sqrt() * z_indep;

        let x_cur = x[0];
        let y_cur = x[1];

        // Euler step for x: dx = [y − κ·x] dt + σ(t) · √dt · Z_corr
        x[0] += (y_cur - p.kappa * x_cur) * dt + sigma_t * dt.sqrt() * z_correlated;

        // Deterministic step for y: dy = [σ(t)² − 2κ·y] dt
        x[1] += (sigma_t * sigma_t - 2.0 * p.kappa * y_cur) * dt;

        // Accumulate the Volterra process for the next step:
        //   Ỹ_{t+dt} = Ỹ_t + ΔỸ.
        work[0] += d_y;
    }

    fn work_size(&self, _process: &CheyetteRoughVolProcess) -> usize {
        1 // work[0] = accumulated RL Volterra process Ỹ(t)
    }
}

#[cfg(test)]
mod tests {
    use super::super::super::process::cheyette_rough::{
        CheyetteRoughVolParams, CheyetteRoughVolProcess,
    };
    use super::*;
    use finstack_core::market_data::term_structures::ForwardVarianceCurve;
    use finstack_core::math::fractional::HurstExponent;

    fn make_process() -> CheyetteRoughVolProcess {
        let sigma_base = ForwardVarianceCurve::flat(0.005).expect("valid flat curve");
        let hurst = HurstExponent::new(0.1).expect("valid hurst");
        let phi_points = vec![(0.0, 0.02), (10.0, 0.03)];
        let params = CheyetteRoughVolParams::new(0.03, sigma_base, hurst, 1.5, -0.3, &phi_points)
            .expect("valid");
        CheyetteRoughVolProcess::new(params)
    }

    #[test]
    fn test_single_step_zero_shocks() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![0.0, 0.0];
        let z = vec![0.0, 0.0, 0.0]; // No shocks
        let mut work = vec![0.0];

        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

        // With x=0, y=0, and zero shocks:
        // dx = [0 - 0.03*0]*dt + sigma(t)*0 = 0
        // dy = [sigma(t)^2 - 0]*dt > 0 (sigma(t) > 0 even with zero Volterra)
        assert!(
            x[0].abs() < 1e-10,
            "x should remain near zero with zero shocks: got {}",
            x[0]
        );
        assert!(
            x[1] > 0.0,
            "y should increase due to sigma(t)^2 term: got {}",
            x[1]
        );
    }

    #[test]
    fn test_single_step_deterministic() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));
        let p = process.params();

        let dt = 0.01_f64;
        let h = p.hurst.value();
        let eta = p.eta;
        let kappa = p.kappa;
        let rho = p.rho;

        let z_indep = 0.5;
        let d_y = 0.02;
        let z_drive = -0.7;
        let x0 = 0.001;
        let y0 = 0.0001;
        let t = 0.25_f64;
        let y_accum = 0.015_f64; // pre-accumulated Volterra level Ỹ_t

        let mut x = vec![x0, y0];
        let z = vec![z_indep, d_y, z_drive];
        let mut work = vec![y_accum];

        disc.step(&process, t, dt, &mut x, &z, &mut work);

        // Manually compute expected result (left-point scheme, variance-
        // lognormal convention): σ(t) from Ỹ_t (before adding ΔỸ).
        let two_h = 2.0 * h;
        let sigma_base = p.sigma_base_value(t);
        let exponent = 0.5 * eta * y_accum - 0.25 * eta * eta * t.powf(two_h);
        let sigma_t = (sigma_base * exponent.exp()).max(0.0);

        // Correlation against the unit-variance driving normal.
        let z_corr = rho * z_drive + (1.0 - rho * rho).max(0.0).sqrt() * z_indep;

        let expected_x = x0 + (y0 - kappa * x0) * dt + sigma_t * dt.sqrt() * z_corr;
        let expected_y = y0 + (sigma_t * sigma_t - 2.0 * kappa * y0) * dt;

        assert!(
            (x[0] - expected_x).abs() < 1e-14,
            "x step mismatch: got {}, expected {}",
            x[0],
            expected_x
        );
        assert!(
            (x[1] - expected_y).abs() < 1e-14,
            "y step mismatch: got {}, expected {}",
            x[1],
            expected_y
        );
        // Volterra accumulation happens after the state update.
        assert!(
            (work[0] - (y_accum + d_y)).abs() < 1e-15,
            "work[0] should accumulate ΔỸ after the step: got {}",
            work[0]
        );
    }

    #[test]
    fn test_sigma_reconstruction() {
        let sigma_base_val = 0.005_f64;
        let h = 0.1_f64;
        let eta = 1.5_f64;
        let t = 0.5_f64;
        let w_h = 0.03_f64;

        // Variance-lognormal convention:
        // σ(t) = σ₀(t) · exp(½·η · Ỹ_t − ¼ · η² · t^{2H})
        let two_h = 2.0 * h;
        let exponent = 0.5 * eta * w_h - 0.25 * eta * eta * t.powf(two_h);
        let sigma = sigma_base_val * exponent.exp();

        // With positive w_h, sigma should be above the base
        assert!(
            sigma > 0.0,
            "Reconstructed sigma should be positive: {sigma}"
        );

        // With zero accumulation, sigma should be below base due to convexity correction
        let exponent_zero = -0.25 * eta * eta * t.powf(two_h);
        let sigma_zero = sigma_base_val * exponent_zero.exp();
        assert!(sigma_zero > 0.0);
        assert!(
            sigma_zero < sigma_base_val,
            "Sigma should be below base level due to convexity correction"
        );

        // The implied variance V = σ² is lognormal with full compensation:
        // V = σ₀²·exp(η·Ỹ − ½η²·t^{2H}). Squaring the reconstruction must
        // reproduce exactly that law's exponent.
        let v = sigma * sigma;
        let v_expected =
            sigma_base_val * sigma_base_val * (eta * w_h - 0.5 * eta * eta * t.powf(two_h)).exp();
        assert!(
            (v - v_expected).abs() < 1e-18,
            "σ² must follow the variance-lognormal law: {v} vs {v_expected}"
        );
    }

    #[test]
    fn test_sigma_uses_left_endpoint() {
        // σ for the step over [t, t+dt] must come from the
        // Volterra level *before* this step's increment. The step's own ΔỸ
        // (z[1]) must therefore have no effect on x or y in this step.
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let t = 0.5_f64;
        let dt = 0.01_f64;
        let y_accum = 0.02_f64;

        let mut x1 = vec![0.001, 0.0001];
        let mut work1 = vec![y_accum];
        disc.step(&process, t, dt, &mut x1, &[0.5, 0.04, -0.7], &mut work1);

        let mut x2 = vec![0.001, 0.0001];
        let mut work2 = vec![y_accum];
        disc.step(&process, t, dt, &mut x2, &[0.5, -0.09, -0.7], &mut work2);

        assert!(
            (x1[0] - x2[0]).abs() < 1e-16 && (x1[1] - x2[1]).abs() < 1e-16,
            "this step's ΔỸ must not affect this step's state update: \
             x1={:?} x2={:?}",
            x1,
            x2
        );
        // ...but it must affect the *next* step through the accumulator.
        assert!(
            (work1[0] - work2[0]).abs() > 1e-3,
            "ΔỸ must accumulate into work[0] for subsequent steps"
        );
    }

    #[test]
    fn test_y_state_is_deterministic_given_sigma() {
        // y update: dy = [σ(t)² − 2κ·y] dt
        // This should be fully determined by sigma(t), y, kappa, and dt.
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let y0 = 0.0001_f64;
        let dt = 0.01_f64;

        // Run with different rate shocks but same accumulated Volterra level —
        // y should be identical.
        let y_accum = 0.02_f64;

        let mut x1 = vec![0.0, y0];
        let mut work1 = vec![y_accum];
        disc.step(&process, 0.5, dt, &mut x1, &[0.5, 0.01, -0.3], &mut work1);

        let mut x2 = vec![0.0, y0];
        let mut work2 = vec![y_accum];
        disc.step(&process, 0.5, dt, &mut x2, &[-1.5, 0.01, 0.8], &mut work2);

        // y should be identical because it depends only on sigma(t) (via the
        // accumulated Volterra level) and y
        assert!(
            (x1[1] - x2[1]).abs() < 1e-15,
            "y should be deterministic given sigma: {} vs {}",
            x1[1],
            x2[1]
        );

        // x should differ because the rate shocks differ
        assert!(
            (x1[0] - x2[0]).abs() > 1e-10,
            "x should differ for different rate shocks"
        );
    }

    #[test]
    fn test_work_buffer_reset_across_paths() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![0.0, 0.0];
        let z = vec![0.0, 0.05, 0.0]; // Non-zero Volterra increment
        let mut work = vec![0.0];

        // Simulate a few steps of path 1
        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);
        disc.step(&process, 0.01, 0.01, &mut x, &z, &mut work);

        let w_h_after_path1 = work[0];
        assert!(
            w_h_after_path1.abs() > 1e-15,
            "Work buffer should accumulate Volterra increments"
        );

        // Start path 2 — engine zeros work buffer before each path
        x[0] = 0.0;
        x[1] = 0.0;
        work[0] = 0.0;
        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

        // After a single step from t=0, work[0] should be exactly the single
        // Volterra increment (accumulator was zeroed by engine before path)
        assert!(
            (work[0] - 0.05).abs() < 1e-15,
            "Work buffer should reset at path start: got {}",
            work[0]
        );
    }

    #[test]
    fn test_work_size() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        assert_eq!(disc.work_size(&process), 1);
    }

    #[test]
    fn test_multiple_steps_no_nan() {
        let process = make_process();
        let disc = CheyetteRoughEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![0.0, 0.0];
        let mut work = vec![0.0];

        let shocks = [
            (0.3, 0.01, -0.2),
            (-0.5, -0.02, 1.1),
            (1.2, 0.03, 0.4),
            (-0.8, -0.01, -1.3),
            (0.1, 0.005, 0.6),
        ];

        let dt = 0.01;
        for (i, &(z0, z1, z2)) in shocks.iter().enumerate() {
            let t = i as f64 * dt;
            let z = vec![z0, z1, z2];
            disc.step(&process, t, dt, &mut x, &z, &mut work);

            assert!(
                x[0].is_finite(),
                "x became non-finite at step {i}: {}",
                x[0]
            );
            assert!(
                x[1].is_finite(),
                "y became non-finite at step {i}: {}",
                x[1]
            );
        }
    }

    /// Variance-lognormal compensation: `E[σ²(t)] = σ₀²(t)` under simulation.
    ///
    /// The σ reconstruction `σ = σ₀·exp(½η·Ỹ − ¼η²·t^{2H})` makes the
    /// variance lognormal with full compensation, so the simulated mean of
    /// σ²(t) must pin to σ₀² at every grid time. The pre-fix σ-lognormal
    /// convention inflates `E[σ²(t)]` by `exp(η²·t^{2H})` — a factor of
    /// ≈2.6 at t=1, η=1.5, H=0.1 — far beyond the MC tolerance here.
    #[test]
    fn simulated_variance_mean_pins_to_base_variance() {
        use super::super::super::rng::fbm::FractionalNoiseGenerator;
        use super::super::super::rng::philox::PhiloxRng;
        use super::super::super::rng::volterra::RiemannLiouvilleVolterra;
        use super::super::super::traits::RandomStream;

        let h = 0.1_f64;
        let eta = 1.5_f64;
        let sigma0 = 0.005_f64;
        let t_end = 1.0_f64;
        let n = 50usize;

        let gen = RiemannLiouvilleVolterra::new(t_end, n, h).expect("valid generator");
        let dt = gen.dt();
        let mut rng = PhiloxRng::new(24680);

        let num_paths = 200_000usize;
        let mut vol_normals = vec![0.0; 2 * n];
        let mut increments = vec![0.0; n];

        // Accumulate σ²(t_k) across paths at a few pinned grid times.
        let check_steps = [10usize, 25, 49];
        let mut sums = [0.0_f64; 3];
        for _ in 0..num_paths {
            rng.fill_std_normals(&mut vol_normals);
            gen.generate(&vol_normals, &mut increments);

            let mut y_accum = 0.0;
            for (k, &incr) in increments.iter().enumerate() {
                y_accum += incr;
                let t_next = (k + 1) as f64 * dt;
                if let Some(pos) = check_steps.iter().position(|&s| s == k) {
                    // σ at the node t_{k+1}, from the accumulated level Ỹ.
                    let exponent = 0.5 * eta * y_accum - 0.25 * eta * eta * t_next.powf(2.0 * h);
                    let sigma_t = sigma0 * exponent.exp();
                    sums[pos] += sigma_t * sigma_t;
                }
            }
        }

        for (pos, &step) in check_steps.iter().enumerate() {
            let mean_var = sums[pos] / num_paths as f64;
            let ratio = mean_var / (sigma0 * sigma0);
            assert!(
                (ratio - 1.0).abs() < 0.05,
                "E[σ²(t)] must pin to σ₀² at step {step}: ratio {ratio}"
            );
        }
    }

    /// The martingale part of x must have zero mean (prior fixes).
    ///
    /// The stochastic increment of x over a step is `σ(t_k)·√dt·Z_corr_k`.
    /// With the left-point σ (independent of this step's shock) and a genuine
    /// Brownian rate driver, `E[σ(t_k)·Z_corr_k] = 0` for every step, so the
    /// path sum `M_T = Σ_k σ(t_k)√dt·Z_corr_k` has mean 0 even at ρ = ±1.
    ///
    /// The pre-fix scheme failed this in two ways: σ was evaluated *after*
    /// adding the step's own ΔỸ (correlating σ with the shock — a spurious
    /// ρ-proportional drift), and the rate driver was the rescaled fBM
    /// increment (autocorrelated across steps, non-unit variance).
    #[test]
    fn stochastic_increment_sum_has_zero_mean() {
        use super::super::super::rng::fbm::FractionalNoiseGenerator;
        use super::super::super::rng::philox::PhiloxRng;
        use super::super::super::rng::volterra::RiemannLiouvilleVolterra;
        use super::super::super::traits::RandomStream;

        let h = 0.1_f64;
        let eta = 1.5_f64;
        let t_end = 1.0_f64;
        let n = 50usize;

        // ρ = 1 maximizes the bias of the pre-fix look-ahead scheme.
        let sigma_base = ForwardVarianceCurve::flat(0.005).expect("valid flat curve");
        let hurst = HurstExponent::new(h).expect("valid hurst");
        let params = CheyetteRoughVolParams::new(0.03, sigma_base, hurst, eta, 1.0, &[(0.0, 0.0)])
            .expect("valid");
        let process = CheyetteRoughVolProcess::new(params);
        let disc = CheyetteRoughEuler::new(hurst);
        let p = process.params();

        let gen = RiemannLiouvilleVolterra::new(t_end, n, h).expect("valid generator");
        let dt = gen.dt();
        let mut rng = PhiloxRng::new(13579);

        let num_paths = 100_000usize;
        let mut vol_normals = vec![0.0; 2 * n];
        let mut rate_normals = vec![0.0; n];
        let mut increments = vec![0.0; n];
        let mut driving = vec![0.0; n];

        let mut sum_m = 0.0; // Σ over paths of M_T
        let mut sum_m_sq = 0.0; // Σ over paths of M_T² (for the MC standard error)
        for _ in 0..num_paths {
            rng.fill_std_normals(&mut vol_normals);
            rng.fill_std_normals(&mut rate_normals);
            gen.generate(&vol_normals, &mut increments);
            gen.driving_normals_into(&vol_normals, &mut driving);

            let mut work = [0.0];
            let mut m_t = 0.0;
            for k in 0..n {
                let t = k as f64 * dt;
                // Recompute σ(t_k) exactly as the discretization does, from
                // the pre-step Volterra level (variance-lognormal convention).
                let exponent = 0.5 * eta * work[0] - 0.25 * eta * eta * t.powf(2.0 * h);
                let sigma_t = (p.sigma_base_value(t) * exponent.exp()).max(0.0);
                // ρ = 1 ⇒ Z_corr = Z̃ (driving normal).
                m_t += sigma_t * dt.sqrt() * driving[k];

                // Advance the Volterra accumulator through the discretization
                // so this test exercises the production step() ordering.
                let mut x = [0.0, 0.0];
                let z = [rate_normals[k], increments[k], driving[k]];
                disc.step(&process, t, dt, &mut x, &z, &mut work);
            }
            sum_m += m_t;
            sum_m_sq += m_t * m_t;
        }

        let npf = num_paths as f64;
        let mean_m = sum_m / npf;
        let var_m = (sum_m_sq / npf - mean_m * mean_m).max(0.0);
        let std_err = (var_m / npf).sqrt();
        // Statistical zero check: |mean| within 5 standard errors. The
        // pre-fix look-ahead bias is a deterministic O(η·σ·dt^{2H}) drift per
        // unit time — orders of magnitude beyond 5 SE at these parameters.
        assert!(
            mean_m.abs() < 5.0 * std_err,
            "martingale increment sum must have zero mean at ρ=1: \
             E[M_T]={mean_m}, SE={std_err}"
        );
    }
}
