#!/usr/bin/env python3
"""Generate Gregorian dates for Chinese lunar festivals (Dragon Boat, Mid-Autumn).

Dragon Boat Festival (端午节) = 5th day of the 5th lunar month.
Mid-Autumn Festival (中秋节)  = 15th day of the 8th lunar month.

Both became national statutory holidays in mainland China in 2008; the tables are
generated for the full validated calendar range (1970-2150) for uniformity with
``chinese_new_year.csv`` / ``cny_generated.rs``. Per-calendar year gating (e.g.
``from_year: 2008``) is applied in the JSON calendar definitions, not here.

Source: the ``lunar-python`` package (6tail lunar library, calibrated to the
official 紫金山天文台 calendar), which agrees with ``lunardate`` across 1970-2099
and extends to 2150.

Regenerate with:

    uv run --with lunar_python finstack-quant/core/data/gen_lunar_festivals.py

Outputs (relative to the crate root ``finstack-quant/core``):
  - data/dragon_boat.csv
  - data/mid_autumn.csv
  - src/generated/festivals_generated.rs
"""

from __future__ import annotations

from pathlib import Path

from lunar_python import Lunar

BASE_YEAR = 1970
END_YEAR = 2150

# (lunar_month, lunar_day) for each festival.
DRAGON_BOAT = (5, 5)
MID_AUTUMN = (8, 15)


def festival_dates(lunar_month: int, lunar_day: int) -> list[tuple[int, int, int]]:
    rows: list[tuple[int, int, int]] = []
    for year in range(BASE_YEAR, END_YEAR + 1):
        solar = Lunar.fromYmd(year, lunar_month, lunar_day).getSolar()
        sy, sm, sd = solar.getYear(), solar.getMonth(), solar.getDay()
        assert sy == year, f"festival {lunar_month}/{lunar_day} for {year} fell in {sy}"
        rows.append((year, sm, sd))
    return rows


def write_csv(path: Path, rows: list[tuple[int, int, int]]) -> None:
    lines = ["year,month,day"]
    lines += [f"{y},{m},{d}" for (y, m, d) in rows]
    path.write_text("\n".join(lines) + "\n")


def render_map(name: str, rows: list[tuple[int, int, int]]) -> str:
    out = [f"static {name}: phf::Map<i32, (u8, u8)> = phf::phf_map! {{"]
    out += [f"    {y}i32 => ({m}, {d})," for (y, m, d) in rows]
    out.append("};")
    return "\n".join(out)


def write_rust(path: Path, dragon: list, autumn: list) -> None:
    body = f"""// Auto-generated by data/gen_lunar_festivals.py - DO NOT EDIT
// Dragon Boat (端午节) and Mid-Autumn (中秋节) festival date lookup tables.
// Coverage: {BASE_YEAR}-{END_YEAR} (matches chinese_new_year / holiday bitset range).

/// Dragon Boat Festival dates as (month, day) tuples, indexed by Gregorian year.
{render_map("DRAGON_BOAT_DATES_MAP", dragon)}

/// Mid-Autumn Festival dates as (month, day) tuples, indexed by Gregorian year.
{render_map("MID_AUTUMN_DATES_MAP", autumn)}

/// Get the Dragon Boat Festival date for a given year, or `None` if unsupported.
#[inline]
pub(crate) fn dragon_boat_date_for_year(year: i32) -> Option<(u8, u8)> {{
    DRAGON_BOAT_DATES_MAP.get(&year).copied()
}}

/// Check whether a date is the Dragon Boat Festival.
#[inline]
pub(crate) fn is_dragon_boat_date(year: i32, month: u8, day: u8) -> bool {{
    DRAGON_BOAT_DATES_MAP
        .get(&year)
        .is_some_and(|&(m, d)| m == month && d == day)
}}

/// Get the Mid-Autumn Festival date for a given year, or `None` if unsupported.
#[inline]
pub(crate) fn mid_autumn_date_for_year(year: i32) -> Option<(u8, u8)> {{
    MID_AUTUMN_DATES_MAP.get(&year).copied()
}}

/// Check whether a date is the Mid-Autumn Festival.
#[inline]
pub(crate) fn is_mid_autumn_date(year: i32, month: u8, day: u8) -> bool {{
    MID_AUTUMN_DATES_MAP
        .get(&year)
        .is_some_and(|&(m, d)| m == month && d == day)
}}
"""
    path.write_text(body)


def main() -> None:
    crate_root = Path(__file__).resolve().parents[1]
    data_dir = crate_root / "data"
    gen_dir = crate_root / "src" / "generated"

    dragon = festival_dates(*DRAGON_BOAT)
    autumn = festival_dates(*MID_AUTUMN)

    write_csv(data_dir / "dragon_boat.csv", dragon)
    write_csv(data_dir / "mid_autumn.csv", autumn)
    write_rust(gen_dir / "festivals_generated.rs", dragon, autumn)
    print(f"Wrote {len(dragon)} Dragon Boat and {len(autumn)} Mid-Autumn dates.")


if __name__ == "__main__":
    main()
