"""Type stubs for ``finstack.factor_model.credit``."""

from __future__ import annotations

class CreditFactorModel:
    @staticmethod
    def from_json(json: str) -> CreditFactorModel: ...
    def to_json(self) -> str: ...
    @property
    def schema_version(self) -> str: ...
    @property
    def as_of(self) -> str: ...
    @property
    def n_levels(self) -> int: ...
    @property
    def n_issuers(self) -> int: ...
    @property
    def n_factors(self) -> int: ...
    def level_names(self) -> list[str]: ...
    def issuer_ids(self) -> list[str]: ...
    def factor_ids(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class CreditCalibrator:
    def __init__(self, config_json: str) -> None: ...
    def calibrate(self, inputs_json: str) -> CreditFactorModel: ...
    def __repr__(self) -> str: ...

class LevelsAtDate:
    @property
    def date(self) -> str: ...
    @property
    def generic(self) -> float: ...
    @property
    def n_levels(self) -> int: ...
    def level_values(self, level_index: int) -> dict[str, float]: ...
    def adder(self) -> dict[str, float]: ...
    def __repr__(self) -> str: ...

class PeriodDecomposition:
    @property
    def from_date(self) -> str: ...
    @property
    def to_date(self) -> str: ...
    @property
    def d_generic(self) -> float: ...
    @property
    def n_levels(self) -> int: ...
    def level_deltas(self, level_index: int) -> dict[str, float]: ...
    def d_adder(self) -> dict[str, float]: ...
    def __repr__(self) -> str: ...

class FactorCovarianceForecast:
    def __init__(self, model: CreditFactorModel) -> None: ...
    def covariance_at(self, horizon: str) -> str: ...
    def idiosyncratic_vol(self, issuer_id: str, horizon: str) -> float: ...
    def factor_model_at(self, horizon: str, risk_measure_json: str) -> str: ...
    def __repr__(self) -> str: ...

def decompose_levels(
    model: CreditFactorModel,
    observed_spreads_json: str,
    observed_generic: float,
    as_of: str,
    runtime_tags_json: str | None = None,
) -> LevelsAtDate: ...
def decompose_period(
    from_levels: LevelsAtDate,
    to_levels: LevelsAtDate,
) -> PeriodDecomposition: ...

__all__ = [
    "CreditFactorModel",
    "CreditCalibrator",
    "LevelsAtDate",
    "PeriodDecomposition",
    "FactorCovarianceForecast",
    "decompose_levels",
    "decompose_period",
]
