//! Monte Carlo pricer for the rough Bergomi (rBergomi) stochastic volatility model.
//!
//! Uses [`RoughBergomiProcess`] with the [`RoughBergomiEuler`] discretization and
//! pre-generated Riemann-Liouville Volterra increments via [`simulate_path_fractional`].
//! Per Bayer-Friz-Gatheral (2016), the rBergomi variance is driven by the
//! Riemann-Liouville Volterra process `Ỹ_t = √(2H)∫₀ᵗ(t−s)^{H−½}dW_s` — a
//! truncated, non-stationary-increment process, distinct from true fractional
//! Brownian motion. The increments are generated by the Bennedsen-Lunde-Pakkanen
//! hybrid scheme (`RiemannLiouvilleVolterra`). This differs from the rough
//! Heston model, which uses standard Brownian motion with a singular kernel.

use super::pricer::{collect_inputs_extended, option_currency, require_european};
use super::types::EquityOption;
use crate::instruments::common_impl::parameters::OptionType;
use crate::instruments::common_impl::traits::Instrument;
use crate::pricer::PricingError;
use finstack_quant_core::dates::Date;
use finstack_quant_core::market_data::context::MarketContext;
use finstack_quant_core::money::Money;

/// Monte Carlo pricer for the rough Bergomi model.
///
/// Simulates spot paths under rBergomi dynamics where the instantaneous variance
/// is a functional of a fractional Brownian motion path:
///
/// ```text
/// V_t = xi_0(t) * exp(eta * W_H(t) - 0.5 * eta^2 * t^{2H})
/// ```
///
/// Model parameters are read from market scalars (all required — no
/// defaults):
///
/// | Scalar Key | Description |
/// |---|---|
/// | `RBERGOMI_ETA` | Vol-of-vol scaling |
/// | `RBERGOMI_HURST` | Hurst exponent |
/// | `RBERGOMI_RHO` | Spot-vol correlation |
///
/// The forward variance curve ξ₀(t) is built from the ATM-forward implied
/// vol term structure of the option's vol surface (total-variance
/// differencing across the surface's expiry strip).
pub(crate) struct EquityOptionRoughBergomiMcPricer {
    /// Number of Monte Carlo paths.
    num_paths: usize,
    /// Number of time steps per path.
    num_steps: usize,
}

impl EquityOptionRoughBergomiMcPricer {
    /// Create a new rBergomi MC pricer with explicit configuration.
    pub(crate) fn new(num_paths: usize, num_steps: usize) -> Self {
        Self {
            num_paths,
            num_steps,
        }
    }
}

impl Default for EquityOptionRoughBergomiMcPricer {
    fn default() -> Self {
        use crate::instruments::common_impl::helpers::mc_defaults;
        Self::new(
            mc_defaults::DEFAULT_MC_PATHS,
            mc_defaults::DEFAULT_ROUGH_VOL_STEPS,
        )
    }
}

/// Bundle of rough-Bergomi parameters resolved from a market context.
///
/// Mirrors `RoughHestonScalars` (rough_heston_market.rs): production pricing
/// requires explicit calibrated scalars so missing model calibration cannot
/// silently fall back to representative defaults.
#[derive(Debug, Clone, Copy)]
pub(crate) struct RoughBergomiScalars {
    /// Vol-of-vol scaling (η).
    pub eta: f64,
    /// Hurst exponent (H).
    pub hurst: f64,
    /// Spot/vol correlation (ρ).
    pub rho: f64,
}

impl RoughBergomiScalars {
    /// Read rough-Bergomi scalars from the market, erroring when any
    /// `RBERGOMI_*` scalar is missing or is not unitless. No numerical
    /// validation is done here; downstream constructors
    /// (`RoughBergomiParams::new`, `HurstExponent::new`) enforce invariants.
    pub(crate) fn from_market_strict(market: &MarketContext) -> finstack_quant_core::Result<Self> {
        use crate::instruments::common_impl::helpers::get_unitless_scalar_strict;
        Ok(Self {
            eta: get_unitless_scalar_strict(market, "RBERGOMI_ETA", "rough Bergomi")?,
            hurst: get_unitless_scalar_strict(market, "RBERGOMI_HURST", "rough Bergomi")?,
            rho: get_unitless_scalar_strict(market, "RBERGOMI_RHO", "rough Bergomi")?,
        })
    }
}

/// Build the forward variance curve ξ₀(t) from the ATM-forward implied vol
/// term structure of the option's vol surface.
///
/// The surface is sampled at the ATM-forward strike `K(u) = S·e^{(r−q)u}`
/// across its expiry strip (clipped to the option maturity `t`, with `t`
/// itself always included). Total variances `w(u) = σ²(u, K(u))·u` are
/// differenced into per-interval forward variances
/// `ξ_i = (w_{i} − w_{i−1})/(u_i − u_{i−1})`, each placed at the interval
/// midpoint. A flat surface therefore reproduces `ForwardVarianceCurve::flat(σ²)`
/// exactly.
///
/// When the instrument carries an `implied_volatility` override, that flat σ
/// wins (standard revaluation convention) and ξ₀ = σ² flat.
fn build_xi0_from_surface(
    market: &MarketContext,
    equity_option: &EquityOption,
    spot: f64,
    r: f64,
    q: f64,
    t: f64,
) -> finstack_quant_core::Result<
    finstack_quant_core::market_data::term_structures::ForwardVarianceCurve,
> {
    use finstack_quant_core::market_data::term_structures::ForwardVarianceCurve;

    if let Some(iv) = equity_option
        .pricing_overrides
        .market_quotes
        .implied_volatility
    {
        return ForwardVarianceCurve::flat(iv * iv);
    }

    let surface = market.get_surface(equity_option.vol_surface_id.as_str())?;

    // Maturity strip: surface expiries strictly inside (0, t), plus t itself.
    let mut strip: Vec<f64> = surface
        .expiries()
        .iter()
        .copied()
        .filter(|&u| u > 1e-12 && u < t - 1e-12)
        .collect();
    strip.push(t);

    // Total variances at the ATM-forward strike, then forward-variance
    // differencing over consecutive intervals (starting from w(0) = 0).
    let mut points = Vec::with_capacity(strip.len());
    let mut prev_u = 0.0;
    let mut prev_w = 0.0;
    for &u in &strip {
        let atm_forward = spot * ((r - q) * u).exp();
        let sigma_u = surface.value_clamped(u, atm_forward);
        let w = sigma_u * sigma_u * u;
        let xi = (w - prev_w) / (u - prev_u);
        if !xi.is_finite() || xi <= 0.0 {
            return Err(finstack_quant_core::Error::Validation(format!(
                "rough Bergomi xi0 strip: non-positive forward variance {xi} over \
                 ({prev_u}, {u}) from surface '{}' — ATM total variance must be \
                 increasing in maturity (no calendar arbitrage)",
                equity_option.vol_surface_id
            )));
        }
        points.push(((prev_u + u) / 2.0, xi));
        prev_u = u;
        prev_w = w;
    }

    ForwardVarianceCurve::from_points(&points)
}

/// Run the fractional MC simulation loop for a concrete payoff type.
#[allow(clippy::too_many_arguments)]
fn simulate_rbergomi<F: finstack_quant_monte_carlo::traits::Payoff>(
    num_paths: usize,
    rng: &mut finstack_quant_monte_carlo::rng::philox::PhiloxRng,
    time_grid: &finstack_quant_monte_carlo::time_grid::TimeGrid,
    process: &finstack_quant_monte_carlo::process::rough_bergomi::RoughBergomiProcess,
    disc: &finstack_quant_monte_carlo::discretization::rough_bergomi::RoughBergomiEuler,
    initial_state: &[f64],
    payoff_template: &F,
    ccy: finstack_quant_core::currency::Currency,
    fbm_gen: &finstack_quant_monte_carlo::rng::volterra::RiemannLiouvilleVolterra,
    num_steps: usize,
    err_ctx: crate::pricer::PricingErrorContext,
) -> std::result::Result<(f64, f64), PricingError> {
    use finstack_quant_monte_carlo::online_stats::OnlineStats;
    use finstack_quant_monte_carlo::rng::fbm::FractionalNoiseGenerator;
    use finstack_quant_monte_carlo::traits::{Discretization, RandomStream, StochasticProcess};

    let num_factors = process.num_factors();
    let work_size = disc.work_size(process);
    let mut state = vec![0.0; process.dim()];
    let mut z = vec![0.0; num_factors];
    let mut work = vec![0.0; work_size];
    // The RL Volterra hybrid scheme draws `normals_per_step` (= 2) i.i.d.
    // normals per time step; size the input buffer accordingly.
    let mut fbm_normals = vec![0.0; num_steps * fbm_gen.normals_per_step()];
    let mut fbm_increments = vec![0.0; num_steps];
    // Per-step unit-variance driving Brownian normals for the spot–vol
    // correlation (injected into z[2]).
    let mut driving_normals = vec![0.0; num_steps];
    // z[1] = Volterra increment ΔỸ; z[2] = driving Brownian normal Z̃.
    let fbm_z_index = 1;
    let drive_z_index = 2;

    let mut stats = OnlineStats::new();

    for _ in 0..num_paths {
        // Generate Riemann-Liouville Volterra increments for this path, plus
        // the driving Brownian normals that the spot leg correlates against.
        rng.fill_std_normals(&mut fbm_normals);
        fbm_gen.generate(&fbm_normals, &mut fbm_increments);
        fbm_gen.driving_normals_into(&fbm_normals, &mut driving_normals);

        let mut payoff = payoff_template.clone();
        payoff.reset();

        let pv = finstack_quant_monte_carlo::engine_fractional::simulate_path_fractional(
            rng,
            time_grid,
            process,
            disc,
            initial_state,
            &mut payoff,
            ccy,
            &fbm_increments,
            fbm_z_index,
            Some((drive_z_index, &driving_normals)),
            &mut state,
            &mut z,
            &mut work,
        )
        .map_err(|e| crate::pricer::PricingError::from_core(e, err_ctx.clone()))?;

        stats.update(pv);
    }

    let stderr = stats.stderr();
    Ok((stats.mean(), if stderr.is_finite() { stderr } else { 0.0 }))
}

impl crate::pricer::Pricer for EquityOptionRoughBergomiMcPricer {
    fn key(&self) -> crate::pricer::PricerKey {
        crate::pricer::PricerKey::new(
            crate::pricer::InstrumentType::EquityOption,
            crate::pricer::ModelKey::MonteCarloRoughBergomi,
        )
    }

    #[tracing::instrument(
        name = "equity_option.rough_bergomi_mc.price_dyn",
        level = "debug",
        skip(self, instrument, market),
        fields(
            inst_id = %instrument.id(),
            as_of = %as_of,
            num_paths = self.num_paths,
            num_steps = self.num_steps,
        ),
        err,
    )]
    fn price_dyn(
        &self,
        instrument: &dyn crate::instruments::common_impl::traits::Instrument,
        market: &MarketContext,
        as_of: Date,
    ) -> std::result::Result<crate::results::ValuationResult, PricingError> {
        let equity_option = instrument
            .as_any()
            .downcast_ref::<EquityOption>()
            .ok_or_else(|| {
                crate::pricer::PricingError::type_mismatch(
                    crate::pricer::InstrumentType::EquityOption,
                    instrument.key(),
                )
            })?;
        require_european(equity_option, "Rough Bergomi Monte Carlo").map_err(|e| {
            crate::pricer::PricingError::model_failure_with_context(
                e.to_string(),
                crate::pricer::PricingErrorContext::from_instrument(equity_option),
            )
        })?;

        if as_of > equity_option.expiry {
            return Ok(crate::results::ValuationResult::stamped(
                equity_option.id(),
                as_of,
                Money::new(0.0, option_currency(equity_option)),
            ));
        }

        // W-31: `collect_inputs_extended` applies the escrowed-dividend model
        // (spot shift + `q = 0`) when `discrete_dividends` is non-empty. The
        // escrowed-dividend identity holds only under Black-Scholes; under the
        // rough Bergomi stochastic-vol dynamics it is invalid, so feeding the
        // escrowed spot into the MC silently mis-prices a single-stock option
        // with discrete dividends. Reject it explicitly rather than price it
        // wrong.
        if equity_option
            .discrete_dividends
            .iter()
            .any(|(ex_date, _)| *ex_date > as_of && *ex_date <= equity_option.expiry)
        {
            return Err(crate::pricer::PricingError::model_failure_with_context(
                "rough Bergomi Monte Carlo pricing does not support discrete \
                 dividends: the escrowed-dividend spot adjustment is a \
                 Black-Scholes-only construct and is invalid under stochastic \
                 volatility. Use the Black-Scholes pricer for discrete \
                 dividends, or supply a continuous dividend yield instead."
                    .to_string(),
                crate::pricer::PricingErrorContext::from_instrument(equity_option)
                    .model(crate::pricer::ModelKey::MonteCarloRoughBergomi),
            ));
        }

        let inputs = collect_inputs_extended(equity_option, market, as_of).map_err(|e| {
            crate::pricer::PricingError::model_failure_with_context(
                e.to_string(),
                crate::pricer::PricingErrorContext::from_instrument(equity_option)
                    .model(crate::pricer::ModelKey::MonteCarloRoughBergomi),
            )
        })?;
        let (spot, r, q, t) = (inputs.spot, inputs.r, inputs.q, inputs.t_vol);

        if t <= 0.0 {
            let intrinsic = match equity_option.option_type {
                OptionType::Call => (spot - equity_option.strike).max(0.0),
                OptionType::Put => (equity_option.strike - spot).max(0.0),
            };
            return Ok(crate::results::ValuationResult::stamped(
                equity_option.id(),
                as_of,
                Money::new(
                    intrinsic * equity_option.notional.amount(),
                    option_currency(equity_option),
                ),
            ));
        }

        let err_ctx = crate::pricer::PricingErrorContext::from_instrument(equity_option)
            .model(crate::pricer::ModelKey::MonteCarloRoughBergomi);

        // Fetch rBergomi parameters — all required, no silent defaults.
        let RoughBergomiScalars { eta, hurst, rho } =
            RoughBergomiScalars::from_market_strict(market)
                .map_err(|e| crate::pricer::PricingError::from_core(e, err_ctx.clone()))?;

        // Build ξ₀(t) from the ATM-forward implied vol term structure.
        let xi = build_xi0_from_surface(market, equity_option, spot, r, q, t)
            .map_err(|e| crate::pricer::PricingError::from_core(e, err_ctx.clone()))?;

        let hurst_exp = finstack_quant_core::math::fractional::HurstExponent::new(hurst)
            .map_err(|e| crate::pricer::PricingError::from_core(e, err_ctx.clone()))?;
        let params = finstack_quant_monte_carlo::process::rough_bergomi::RoughBergomiParams::new(
            r, q, hurst_exp, eta, rho, xi,
        )
        .map_err(|e| crate::pricer::PricingError::from_core(e, err_ctx.clone()))?;
        let process =
            finstack_quant_monte_carlo::process::rough_bergomi::RoughBergomiProcess::new(params);

        // Build time grid
        let time_grid = finstack_quant_monte_carlo::time_grid::TimeGrid::uniform(t, self.num_steps)
            .map_err(|e| crate::pricer::PricingError::from_core(e, err_ctx.clone()))?;

        // Build discretization and the Riemann-Liouville Volterra generator.
        // rBergomi requires the RL Volterra process Ỹ_t = √(2H)∫₀ᵗ(t−s)^{H−½}dW_s
        // (Bayer-Friz-Gatheral 2016) — not true fBM — so the noise driver is the
        // Bennedsen-Lunde-Pakkanen hybrid-scheme generator.
        let disc =
            finstack_quant_monte_carlo::discretization::rough_bergomi::RoughBergomiEuler::new(
                hurst_exp,
            );
        let fbm_gen = finstack_quant_monte_carlo::rng::volterra::RiemannLiouvilleVolterra::new(
            t,
            self.num_steps,
            hurst,
        )
        .map_err(|e| crate::pricer::PricingError::from_core(e, err_ctx.clone()))?;

        let ccy = option_currency(equity_option);
        let initial_state = [spot];

        // Derive deterministic seed from instrument id
        let seed_val =
            if let Some(ref scenario) = equity_option.pricing_overrides.metrics.mc_seed_scenario {
                finstack_quant_monte_carlo::seed::derive_seed(&equity_option.id, scenario)
            } else {
                finstack_quant_monte_carlo::seed::derive_seed(&equity_option.id, "base")
            };
        let mut rng = finstack_quant_monte_carlo::rng::philox::PhiloxRng::new(seed_val);

        // Resolve and cap the path count via the workspace helper before
        // allocating, so a malicious or typo'd `mc_paths` override can't OOM
        // the host.
        let num_paths = crate::instruments::common_impl::helpers::resolve_mc_paths(
            equity_option.pricing_overrides.model_config.mc_paths,
            self.num_paths,
        )
        .map_err(|e| crate::pricer::PricingError::from_core(e, err_ctx.clone()))?;

        let (mean_pv, stderr_undisc) = match equity_option.option_type {
            OptionType::Call => {
                let payoff = finstack_quant_monte_carlo::payoff::vanilla::EuropeanCall::new(
                    equity_option.strike,
                    equity_option.notional.amount(),
                    self.num_steps,
                );
                simulate_rbergomi(
                    num_paths,
                    &mut rng,
                    &time_grid,
                    &process,
                    &disc,
                    &initial_state,
                    &payoff,
                    ccy,
                    &fbm_gen,
                    self.num_steps,
                    err_ctx,
                )?
            }
            OptionType::Put => {
                let payoff = finstack_quant_monte_carlo::payoff::vanilla::EuropeanPut::new(
                    equity_option.strike,
                    equity_option.notional.amount(),
                    self.num_steps,
                );
                simulate_rbergomi(
                    num_paths,
                    &mut rng,
                    &time_grid,
                    &process,
                    &disc,
                    &initial_state,
                    &payoff,
                    ccy,
                    &fbm_gen,
                    self.num_steps,
                    err_ctx,
                )?
            }
        };

        // Vanilla payoffs from `simulate_path_fractional` are undiscounted
        // terminal payoffs; discount the path mean (and stderr) to present
        // value, matching the Heston and rough-Heston MC pricers.
        let df = (-r * t).exp();
        let pv = Money::new(mean_pv * df, ccy);
        let mut result = crate::results::ValuationResult::stamped(equity_option.id(), as_of, pv);
        let stderr = stderr_undisc * df;
        if stderr > 0.0 {
            result
                .measures
                .insert(crate::metrics::MetricId::custom("mc_stderr"), stderr);
        }
        Ok(result)
    }
}
