import { readFile, writeFile } from "node:fs/promises";
import prettier from "prettier";
const catalogue = JSON.parse(
  await readFile(
    new URL("../src/generated/catalogue.json", import.meta.url),
    "utf8",
  ),
);
const target = new URL(
  "../../docs-site/content/docs/registry/instruments.mdx",
  import.meta.url,
);
const text = await prettier.format(
  `---
title: Instrument catalogue
description: Canonical examples for every discovered instrument type.
---

{/* Generated by finstack-quant-ui/scripts/catalogue-docs.mjs; do not edit. */}

The catalogue contains ${catalogue.length} canonical instrument examples. Forms share the generated renderer and native validation. Schemas and examples load on selection. Group labels are navigation categories; the canonical schema ownership is retained in the inventory.

Select an instrument below to open its canonical example in the workbench.

| Instrument | Group | Canonical example ID |
| --- | --- | --- |
${catalogue.map((entry) => `| [${entry.title}](/docs/registry/workbench?instrument=${encodeURIComponent(entry.type)}) | ${entry.group.replaceAll("_", " ")} | ${entry.exampleId} |`).join("\n")}
`,
  { parser: "mdx" },
);
if (process.argv.includes("--check")) {
  if ((await readFile(target, "utf8").catch(() => null)) !== text)
    throw new Error("Generated instrument catalogue documentation is stale");
} else await writeFile(target, text);
