import { glob, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import { z } from "zod";
import { bundleRoot, json, readContracts } from "./schema.mjs";
import { converterSchema, linkSchema } from "../src/schema.mjs";
import { generateProvenance } from "./provenance.mjs";
import { externalize, planSharedDefs, sharedRefNames } from "./share-defs.mjs";

export const packageRoot = fileURLToPath(new URL("..", import.meta.url));
export const repoRoot = resolve(packageRoot, "..");
const header = "// Generated by scripts/gen.mjs; do not edit.\n";

/** Discover filenames each run; examples exercise canonical contracts, never define them. */
export async function discoverFixtures(repo, contracts) {
  const fixtures = [];
  const roots = [...contracts.values()];
  const byFile = (name) =>
    roots.find((entry) => entry.source.endsWith(`/${name}.schema.json`));
  for (const [kind, pattern] of [
    [
      "instrument",
      "finstack-quant/valuations/tests/instruments/json_examples/*.json",
    ],
    [
      "calibration-input",
      "finstack-quant/calibration/examples/market_bootstrap/*.json",
    ],
    [
      "statement-model",
      "finstack-quant/statements/tests/data/canonical/financial_model.json",
    ],
  ]) {
    const paths = [];
    for await (const path of glob(pattern, { cwd: repo })) paths.push(path);
    for (const source of paths.sort()) {
      const text = await readFile(resolve(repo, source), "utf8");
      const value = JSON.parse(text);
      const contract =
        kind === "instrument"
          ? byFile(value.instrument?.type)
          : byFile(kind === "statement-model" ? "financial_model_spec" : "calibration");
      if (
        !contract ||
        (kind === "instrument" && !contract.$id.includes("/instrument/1/"))
      )
        throw new Error(`No canonical contract for ${source}`);
      fixtures.push({ kind, source, schema: contract.$id, text });
      if (Object.hasOwn(value, "final_market")) {
        fixtures.push({
          kind: "calibration-output",
          source,
          pointer: "/final_market",
          schema: byFile("market_context_state").$id,
          text: json(value.final_market),
        });
      }
    }
  }
  // The existing facade test market is a market snapshot, not a calibration envelope.
  for await (const source of glob(
    "finstack-quant/valuations/tests/fixtures/production_cds_option.json",
    { cwd: repo },
  )) {
    const value = JSON.parse(await readFile(resolve(repo, source), "utf8"));
    fixtures.push({
      kind: "market-input",
      source,
      pointer: "/market",
      schema: byFile("market_context_state").$id,
      text: json(value.market),
    });
  }
  return fixtures;
}

export async function generate(repo = repoRoot) {
  const contracts = await readContracts(repo);
  const fixtures = await discoverFixtures(repo, contracts);
  const roots = [...contracts.values()]
    .filter(
      (entry) =>
        /\/instrument\/1\/[^/]+\/[^/]+\.schema\.json$/.test(entry.$id) ||
        [
          "calibration",
          "market_context_state",
          "valuation_result",
          "instrument_cashflow",
          "financial_model_spec",
          "statement_result",
        ].some((name) => entry.$id.endsWith(`/${name}.schema.json`)),
    )
    .sort((a, b) => a.$id.localeCompare(b.$id));
  const files = new Map();
  const catalogue = [];
  const catalogueMetadata = [];
  const names = new Set();
  const sharedPlan = planSharedDefs(roots.map((root) => root.schema));
  const wideIds = new Set(
    roots
      .filter((root) => Object.keys(root.schema.$defs ?? {}).length > 80)
      .map((root) => root.$id),
  );
  let sharedBundle = null;
  if (sharedPlan.schema) {
    sharedBundle = await bundleRoot(sharedPlan.schema.$id, contracts, {
      schema: sharedPlan.schema,
      stableDefinitionNames: true,
    });
    sharedBundle = {
      schema: structuredClone(sharedBundle.schema),
      metadata: structuredClone(sharedBundle.metadata),
    };
    files.set("defs/shared.json", json(sharedBundle.schema));
    files.set(
      "meta/shared.ts",
      `${header}export default ${JSON.stringify(sharedBundle.metadata, null, 2)};\n`,
    );
    const sharedTypes = converterSchema(
      structuredClone(sharedBundle.schema),
      "typescript",
    );
    sharedTypes.title = "SharedDefs";
    files.set(
      "types/shared.ts",
      await compile(sharedTypes, "SharedDefs", {
        bannerComment: `${header}// JSON wire shape only; runtime constraints remain in the schema.`,
        unreachableDefinitions: true,
        unknownAny: true,
        $refOptions: { resolve: { file: false, http: false } },
      }),
    );
  }
  for (const root of roots) {
    const name = root.$id.split("/").at(-1).replace(".schema.json", "");
    if (names.has(name)) throw new Error(`Duplicate output name: ${name}`);
    names.add(name);
    // Statement definitions reference one another extensively; keep that
    // published root closed so generated TS follows its complete graph.
    const wide = wideIds.has(root.$id) && !root.$id.includes("/statements/1/");
    const { schema, metadata } = await bundleRoot(
      root.$id,
      contracts,
      wide ? { schema: externalize(root.schema, sharedPlan.names) } : {},
    );
    const closed = wide ? linkSchema(schema, sharedBundle.schema) : schema;
    // Conversion here makes unsupported constructs a generation failure. Runtime
    // conversion stays lazy and cached by the generated module's ESM identity.
    const validator = z.fromJSONSchema(
      converterSchema(structuredClone(closed)),
    );
    const examples = fixtures.filter((fixture) => fixture.schema === root.$id);
    for (const fixture of examples) {
      const value = JSON.parse(fixture.text);
      // A calibration fixture can include the returned market alongside inputs.
      if (fixture.kind === "calibration-input") {
        delete value.$schema;
        delete value.final_market;
      }
      const result = validator.safeParse(value);
      if (!result.success)
        throw new Error(
          `Fixture failed ${fixture.source}: ${JSON.stringify(result.error.issues).slice(0, 4000)}`,
        );
    }
    files.set(`schemas/${name}.json`, json(schema));
    files.set(
      `meta/${name}.ts`,
      `${header}export default ${JSON.stringify(metadata, null, 2)};\n`,
    );
    let typeInput = structuredClone(schema);
    const localNames = new Map();
    if (wide && typeInput.$defs) {
      let index = 0;
      for (const key of Object.keys(typeInput.$defs))
        localNames.set(key, `Local${index++}`);
      const retarget = (node) => {
        if (Array.isArray(node)) return node.map(retarget);
        if (!node || typeof node !== "object") return node;
        const next = {};
        for (const [key, value] of Object.entries(node)) {
          if (
            key === "$ref" &&
            typeof value === "string" &&
            value.startsWith("#/$defs/")
          ) {
            const id = value.slice("#/$defs/".length).split("/")[0];
            if (localNames.has(id)) {
              next[key] =
                `#/$defs/${localNames.get(id)}${value.slice(`#/$defs/${id}`.length)}`;
              continue;
            }
          }
          next[key] = retarget(value);
        }
        return next;
      };
      const defs = Object.fromEntries(
        [...localNames].map(([key, title]) => [
          title,
          retarget(typeInput.$defs[key]),
        ]),
      );
      typeInput = retarget({ ...typeInput, $defs: {} });
      typeInput.$defs = defs;
    }
    const typeSchema = converterSchema(typeInput, "typescript");
    typeSchema.title = `${name
      .split("_")
      .map((word) => word[0].toUpperCase() + word.slice(1))
      .join("")}Wire`;
    const banner = `${header}// JSON wire shape only; runtime constraints remain in the schema.\n`;
    const sharedTypesResolver = sharedBundle && {
      resolve: {
        file: false,
        http: false,
        canonical: {
          order: 1,
          canRead: (file) =>
            String(file.url).split("#")[0] === sharedBundle.schema.$id,
          read: () => structuredClone(sharedBundle.schema),
        },
      },
    };
    let types = await compile(typeSchema, typeSchema.title, {
      bannerComment: banner,
      unreachableDefinitions: false,
      unknownAny: true,
      declareExternallyReferenced: !wide,
      $refOptions: wide
        ? sharedTypesResolver
        : { resolve: { file: false, http: false } },
    });
    if (wide) {
      const referenced = new Set(sharedRefNames(schema));
      for (const [title, def] of Object.entries(typeInput.$defs ?? {})) {
        const local = converterSchema(
          structuredClone({ ...def, title }),
          "typescript",
        );
        const part = await compile(local, title, {
          bannerComment: "",
          unreachableDefinitions: false,
          unknownAny: true,
          declareExternallyReferenced: false,
          $refOptions: sharedTypesResolver,
        });
        types += `\n${part.trim()}\n`;
        for (const defName of sharedRefNames(def)) referenced.add(defName);
      }
      const used = [...referenced]
        .filter((defName) => new RegExp(`\\b${defName}\\b`).test(types))
        .sort();
      if (used.length)
        types = types.replace(
          banner,
          `${banner}import type { ${used.join(", ")} } from "./shared";\n`,
        );
    }
    files.set(`types/${name}.ts`, types);
    if (root.$id.includes("/instrument/1/")) {
      if (examples.length !== 1)
        throw new Error(
          `Expected one canonical example for ${name}, found ${examples.length}`,
        );
      const type = JSON.parse(examples[0].text).instrument.type;
      if (type !== name) throw new Error(`Instrument tag mismatch for ${name}`);
      files.set(`examples/${name}.json`, examples[0].text);
      files.set(
        `instrument/${name}.ts`,
        wide
          ? `${header}import { createWireCodec } from "../../codec.mjs";\nimport { linkSchema } from "../../schema.mjs";\nimport source from "../schemas/${name}.json";\nimport sharedSchema from "../defs/shared.json";\nimport sharedMetadata from "../meta/shared";\nimport localMetadata from "../meta/${name}";\nexport { default as example } from "../examples/${name}.json";\nexport type * from "../types/${name}";\nexport const schema = linkSchema(source, sharedSchema);\nexport const metadata = [\n  ...localMetadata,\n  ...sharedMetadata.filter((entry) => entry.path.startsWith("#/$defs/")),\n];\nexport const codec = createWireCodec(schema);\nexport const validator = codec.validator;\n`
          : `${header}import { createWireCodec } from "../../codec.mjs";\nimport schema from "../schemas/${name}.json";\nexport { default as metadata } from "../meta/${name}";\nexport { default as example } from "../examples/${name}.json";\nexport type * from "../types/${name}";\nexport { schema };\nexport const codec = createWireCodec(schema);\nexport const validator = codec.validator;\n`,
      );
      const schemaGroup = root.$id.split("/").at(-2);
      const group = [
        "real_estate_asset",
        "levered_real_estate_equity",
        "private_markets_fund",
      ].includes(type)
        ? "real_assets"
        : schemaGroup === "credit_derivatives"
          ? "credit"
          : schemaGroup;
      const entry = {
        type,
        title: root.title,
        group,
        schemaGroup,
        exampleSource: examples[0].source,
        exampleId: JSON.parse(examples[0].text).instrument.spec.id,
      };
      catalogueMetadata.push(entry);
      catalogue.push(
        `  { type: ${JSON.stringify(type)}, title: ${JSON.stringify(root.title)}, group: ${JSON.stringify(group)}, loader: () => import("./instrument/${name}") }`,
      );
    }
  }
  files.set(
    "instruments.ts",
    `${header}export const instruments = [\n${catalogue.join(",\n")}\n] as const;\n`,
  );
  files.set("catalogue.json", json(catalogueMetadata));
  files.set("fixtures.json", json(fixtures.map(({ text, ...entry }) => entry)));
  files.set(
    "roots.json",
    json(
      roots.map((root) => ({
        uri: root.$id,
        source: root.source,
        schema: `schemas/${root.$id.split("/").at(-1).replace(".schema", "")}`,
      })),
    ),
  );
  const primitiveContracts = {};
  for (const name of [
    "decimal",
    "day_count",
    "business_day_convention",
    "tenor",
  ]) {
    const entry = [...contracts.values()].find((entry) =>
      entry.source.endsWith(`/common/1/${name}.schema.json`),
    );
    if (!entry) throw new Error(`Missing primitive contract: ${name}`);
    primitiveContracts[name] = { source: entry.source, schema: entry.schema };
  }
  files.set("primitive-contracts.json", json(primitiveContracts));
  return files;
}

export async function writeGenerated(files, output, check) {
  const existing = [];
  for await (const entry of glob("**/*", {
    cwd: output,
    withFileTypes: true,
  })) {
    if (entry.isFile())
      existing.push(relative(output, resolve(entry.parentPath, entry.name)));
  }
  const drift = existing.filter((file) => !files.has(file));
  for (const [file, contents] of files) {
    const path = resolve(output, file);
    if (check) {
      if ((await readFile(path, "utf8").catch(() => null)) !== contents)
        drift.push(file);
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, contents);
    }
  }
  if (check && drift.length)
    throw new Error(
      `Generated UI drift:\n${drift.join("\n")}\nRun mise run ui-gen.`,
    );
  if (!check) for (const file of drift) await rm(resolve(output, file));
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const files = await generate();
  const check = process.argv.includes("--check");
  const provenance = await generateProvenance(
    repoRoot,
    await readContracts(repoRoot),
    files.get("fixtures.json"),
  );
  files.set("curve-views.json", json(provenance.curves));
  await writeGenerated(files, resolve(packageRoot, "src/generated"), check);
  const inventoryPath = resolve(packageRoot, "src/contract-provenance.json");
  const inventory = json(provenance.inventory);
  if (check) {
    if ((await readFile(inventoryPath, "utf8").catch(() => null)) !== inventory)
      throw new Error("Contract provenance drift; run mise run ui-gen.");
  } else await writeFile(inventoryPath, inventory);
  console.log(
    `${process.argv.includes("--check") ? "Checked" : "Generated"} ${files.size} UI contract files.`,
  );
}
