import { glob, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import { z } from "zod";
import { bundleRoot, json, readContracts } from "./schema.mjs";
import { converterSchema } from "../src/schema.mjs";

export const packageRoot = fileURLToPath(new URL("..", import.meta.url));
export const repoRoot = resolve(packageRoot, "..");
const header = "// Generated by scripts/gen.mjs; do not edit.\n";

/** Discover filenames each run; examples exercise canonical contracts, never define them. */
export async function discoverFixtures(repo, contracts) {
  const fixtures = [];
  const roots = [...contracts.values()];
  const byFile = (name) =>
    roots.find((entry) => entry.source.endsWith(`/${name}.schema.json`));
  for (const [kind, pattern] of [
    [
      "instrument",
      "finstack-quant/valuations/tests/instruments/json_examples/*.json",
    ],
    [
      "calibration-input",
      "finstack-quant/calibration/examples/market_bootstrap/*.json",
    ],
  ]) {
    const paths = [];
    for await (const path of glob(pattern, { cwd: repo })) paths.push(path);
    for (const source of paths.sort()) {
      const text = await readFile(resolve(repo, source), "utf8");
      const value = JSON.parse(text);
      const contract =
        kind === "instrument"
          ? byFile(value.instrument?.type)
          : byFile("calibration");
      if (
        !contract ||
        (kind === "instrument" && !contract.$id.includes("/instrument/1/"))
      )
        throw new Error(`No canonical contract for ${source}`);
      fixtures.push({ kind, source, schema: contract.$id, text });
      if (Object.hasOwn(value, "final_market")) {
        fixtures.push({
          kind: "calibration-output",
          source,
          pointer: "/final_market",
          schema: byFile("market_context_state").$id,
          text: json(value.final_market),
        });
      }
    }
  }
  return fixtures;
}

export async function generate(repo = repoRoot) {
  const contracts = await readContracts(repo);
  const fixtures = await discoverFixtures(repo, contracts);
  const roots = [...contracts.values()]
    .filter(
      (entry) =>
        /\/instrument\/1\/[^/]+\/[^/]+\.schema\.json$/.test(entry.$id) ||
        ["calibration", "market_context_state", "valuation_result"].some(
          (name) => entry.$id.endsWith(`/${name}.schema.json`),
        ),
    )
    .sort((a, b) => a.$id.localeCompare(b.$id));
  const files = new Map();
  const catalogue = [];
  const names = new Set();
  for (const root of roots) {
    const name = root.$id.split("/").at(-1).replace(".schema.json", "");
    if (names.has(name)) throw new Error(`Duplicate output name: ${name}`);
    names.add(name);
    const { schema, metadata } = await bundleRoot(root.$id, contracts);
    // Conversion here makes unsupported constructs a generation failure. Runtime
    // conversion stays lazy and cached by the generated module's ESM identity.
    const validator = z.fromJSONSchema(converterSchema(schema));
    const examples = fixtures.filter((fixture) => fixture.schema === root.$id);
    for (const fixture of examples) {
      const value = JSON.parse(fixture.text);
      // A calibration fixture can include the returned market alongside inputs.
      if (fixture.kind === "calibration-input") {
        delete value.$schema;
        delete value.final_market;
      }
      const result = validator.safeParse(value);
      if (!result.success)
        throw new Error(
          `Fixture failed ${fixture.source}: ${JSON.stringify(result.error.issues).slice(0, 4000)}`,
        );
    }
    files.set(`schemas/${name}.json`, json(schema));
    files.set(
      `meta/${name}.ts`,
      `${header}export default ${JSON.stringify(metadata, null, 2)};\n`,
    );
    const typeSchema = converterSchema(schema, "typescript");
    typeSchema.title = `${name
      .split("_")
      .map((word) => word[0].toUpperCase() + word.slice(1))
      .join("")}Wire`;
    files.set(
      `types/${name}.ts`,
      await compile(typeSchema, typeSchema.title, {
        bannerComment: `${header}// JSON wire shape only; runtime constraints remain in the schema.`,
        unreachableDefinitions: false,
        unknownAny: true,
        $refOptions: { resolve: { file: false, http: false } },
      }),
    );
    if (root.$id.includes("/instrument/1/")) {
      if (examples.length !== 1)
        throw new Error(
          `Expected one canonical example for ${name}, found ${examples.length}`,
        );
      const type = JSON.parse(examples[0].text).instrument.type;
      if (type !== name) throw new Error(`Instrument tag mismatch for ${name}`);
      files.set(`examples/${name}.json`, examples[0].text);
      files.set(
        `instrument/${name}.ts`,
        `${header}import { z } from "zod";\nimport { converterSchema } from "../../schema.mjs";\nimport schema from "../schemas/${name}.json";\nexport { default as metadata } from "../meta/${name}";\nexport { default as example } from "../examples/${name}.json";\nexport type * from "../types/${name}";\nexport { schema };\nexport const validator = z.fromJSONSchema(converterSchema(schema));\n`,
      );
      catalogue.push(
        `  { type: ${JSON.stringify(type)}, title: ${JSON.stringify(root.title)}, group: ${JSON.stringify(root.$id.split("/").at(-2))}, loader: () => import("./instrument/${name}") }`,
      );
    }
  }
  files.set(
    "instruments.ts",
    `${header}export const instruments = [\n${catalogue.join(",\n")}\n] as const;\n`,
  );
  files.set("fixtures.json", json(fixtures.map(({ text, ...entry }) => entry)));
  files.set(
    "roots.json",
    json(
      roots.map((root) => ({
        uri: root.$id,
        source: root.source,
        schema: `schemas/${root.$id.split("/").at(-1).replace(".schema", "")}`,
      })),
    ),
  );
  return files;
}

export async function writeGenerated(files, output, check) {
  const existing = [];
  for await (const entry of glob("**/*", {
    cwd: output,
    withFileTypes: true,
  })) {
    if (entry.isFile())
      existing.push(relative(output, resolve(entry.parentPath, entry.name)));
  }
  const drift = existing.filter((file) => !files.has(file));
  for (const [file, contents] of files) {
    const path = resolve(output, file);
    if (check) {
      if ((await readFile(path, "utf8").catch(() => null)) !== contents)
        drift.push(file);
    } else {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, contents);
    }
  }
  if (check && drift.length)
    throw new Error(
      `Generated UI drift:\n${drift.join("\n")}\nRun mise run ui-gen.`,
    );
  if (!check) for (const file of drift) await rm(resolve(output, file));
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const files = await generate();
  await writeGenerated(
    files,
    resolve(packageRoot, "src/generated"),
    process.argv.includes("--check"),
  );
  console.log(
    `${process.argv.includes("--check") ? "Checked" : "Generated"} ${files.size} UI contract files.`,
  );
}
