import * as wasm from '../pkg/finstack_quant_wasm.js';

export const core = {
  Currency: wasm.Currency,
  Money: wasm.Money,
  Rate: wasm.Rate,
  Bps: wasm.Bps,
  Percentage: wasm.Percentage,
  DayCount: wasm.DayCount,
  DayCountContext: wasm.DayCountContext,
  Tenor: wasm.Tenor,
  createDate: wasm.createDate,
  dateFromEpochDays: wasm.dateFromEpochDays,
  adjust: wasm.adjust,
  availableCalendars: wasm.availableCalendars,
  DiscountCurve: wasm.DiscountCurve,
  HazardCurve: wasm.HazardCurve,
  ForwardCurve: wasm.ForwardCurve,
  VolCube: wasm.VolCube,
  FxDeltaVolSurface: wasm.FxDeltaVolSurface,
  FxConversionPolicy: wasm.FxConversionPolicy,
  FxRateResult: wasm.FxRateResult,
  FxMatrix: wasm.FxMatrix,
  FxQuoteConvention: wasm.FxQuoteConvention,
  FxPairConvention: wasm.FxPairConvention,
  fxMarketPair: wasm.fxMarketPair,
  fxPairConvention: wasm.fxPairConvention,
  fxPipSize: wasm.fxPipSize,
  invertFxRate: wasm.invertFxRate,
  applyLowerTriangular: wasm.applyLowerTriangular,
  choleskyDecomposition: wasm.choleskyDecomposition,
  choleskySolve: wasm.choleskySolve,
  mean: wasm.mean,
  variance: wasm.variance,
  populationVariance: wasm.populationVariance,
  correlation: wasm.correlation,
  covariance: wasm.covariance,
  quantile: wasm.quantile,
  normCdf: wasm.normCdf,
  logNormCdf: wasm.logNormCdf,
  normPdf: wasm.normPdf,
  standardNormalInvCdf: wasm.standardNormalInvCdf,
  erf: wasm.erf,
  lnGamma: wasm.lnGamma,
  kahanSum: wasm.kahanSum,
  neumaierSum: wasm.neumaierSum,
  longestPositiveRun: wasm.longestPositiveRun,
};
