import * as wasm from '../pkg/finstack_quant_wasm.js';
import { schema } from './margin/schema.js';

// Rust `compute_mva` takes an optional own-survival curve. wasm-bindgen cannot
// borrow an optional handle, so the two raw exports are one Rust call each and
// the published function picks between them.
const computeMva = (imProfile, fundingSpreadCurve, discountCurve, survivalCurve = undefined) =>
  survivalCurve === undefined || survivalCurve === null
    ? wasm.computeMvaWithoutSurvival(imProfile, fundingSpreadCurve, discountCurve)
    : wasm.computeMvaWithSurvival(imProfile, fundingSpreadCurve, discountCurve, survivalCurve);

export const margin = {
  csaUsdRegulatoryJson: wasm.csaUsdRegulatoryJson,
  csaEurRegulatoryJson: wasm.csaEurRegulatoryJson,
  validateCsaJson: wasm.validateCsaJson,
  calculateVm: wasm.calculateVm,
  computeBilateralXva: wasm.computeBilateralXva,
  FrtbSbaEngine: wasm.FrtbSbaEngine,
  FrtbSensitivities: wasm.FrtbSensitivities,
  HaircutImCalculator: wasm.HaircutImCalculator,
  SaCcrEngine: wasm.SaCcrEngine,
  ScheduleImCalculator: wasm.ScheduleImCalculator,
  SimmCalculator: wasm.SimmCalculator,
  SimmSensitivities: wasm.SimmSensitivities,
  VmCalculator: wasm.VmCalculator,
  constants: wasm.marginConstants,
  computeMva,
  clearingStatusBilateral: wasm.clearingStatusBilateral,
  clearingStatusCleared: wasm.clearingStatusCleared,
  collateralAssetClassAgencyBonds: wasm.collateralAssetClassAgencyBonds,
  collateralAssetClassCash: wasm.collateralAssetClassCash,
  collateralAssetClassCorporateBonds: wasm.collateralAssetClassCorporateBonds,
  collateralAssetClassCoveredBonds: wasm.collateralAssetClassCoveredBonds,
  collateralAssetClassEquity: wasm.collateralAssetClassEquity,
  collateralAssetClassFromStr: wasm.collateralAssetClassFromStr,
  collateralAssetClassFxAddon: wasm.collateralAssetClassFxAddon,
  collateralAssetClassGold: wasm.collateralAssetClassGold,
  collateralAssetClassGovernmentBonds: wasm.collateralAssetClassGovernmentBonds,
  collateralAssetClassMutualFunds: wasm.collateralAssetClassMutualFunds,
  collateralAssetClassStandardHaircut: wasm.collateralAssetClassStandardHaircut,
  csaSpecApplyImTerms: wasm.csaSpecApplyImTerms,
  csaSpecEurRegulatory: wasm.csaSpecEurRegulatory,
  csaSpecRegulatory: wasm.csaSpecRegulatory,
  csaSpecUsdRegulatory: wasm.csaSpecUsdRegulatory,
  csaSpecValidate: wasm.csaSpecValidate,
  csaSpecWithIm: wasm.csaSpecWithIm,
  csaSpecWithVmThreshold: wasm.csaSpecWithVmThreshold,
  eligibleCollateralScheduleBcbsStandard: wasm.eligibleCollateralScheduleBcbsStandard,
  eligibleCollateralScheduleCashOnly: wasm.eligibleCollateralScheduleCashOnly,
  eligibleCollateralScheduleCheckConcentrationLimits:
    wasm.eligibleCollateralScheduleCheckConcentrationLimits,
  eligibleCollateralScheduleHaircutFor: wasm.eligibleCollateralScheduleHaircutFor,
  eligibleCollateralScheduleHaircutForMaturity: wasm.eligibleCollateralScheduleHaircutForMaturity,
  eligibleCollateralScheduleIsEligible: wasm.eligibleCollateralScheduleIsEligible,
  eligibleCollateralScheduleUsTreasuries: wasm.eligibleCollateralScheduleUsTreasuries,
  excessCollateral: wasm.excessCollateral,
  excessCollateralExcessPercentage: wasm.excessCollateralExcessPercentage,
  excessCollateralHasExcess: wasm.excessCollateralHasExcess,
  excessCollateralHasShortfall: wasm.excessCollateralHasShortfall,
  exposureProfileValidate: wasm.exposureProfileValidate,
  frtbSbaCharge: wasm.frtbSbaCharge,
  fundingConfigEffectiveBenefitBp: wasm.fundingConfigEffectiveBenefitBp,
  fundingConfigEffectiveMarginSpreadBp: wasm.fundingConfigEffectiveMarginSpreadBp,
  haircut01: wasm.haircut01,
  haircut01HaircutBp: wasm.haircut01HaircutBp,
  imDecayProfileConstant: wasm.imDecayProfileConstant,
  imDecayProfileFactor: wasm.imDecayProfileFactor,
  imDecayProfileLinearToMaturity: wasm.imDecayProfileLinearToMaturity,
  imDecayProfileSqrtTime: wasm.imDecayProfileSqrtTime,
  imMethodologyClearingHouse: wasm.imMethodologyClearingHouse,
  imMethodologyFromStr: wasm.imMethodologyFromStr,
  imMethodologyHaircut: wasm.imMethodologyHaircut,
  imMethodologyInternalModel: wasm.imMethodologyInternalModel,
  imMethodologySchedule: wasm.imMethodologySchedule,
  imMethodologySimm: wasm.imMethodologySimm,
  imProfileFromSimm: wasm.imProfileFromSimm,
  imProfileValidate: wasm.imProfileValidate,
  imResultBreakdownAmount: wasm.imResultBreakdownAmount,
  imResultBreakdownKeys: wasm.imResultBreakdownKeys,
  marginCallTypeFromStr: wasm.marginCallTypeFromStr,
  marginCallTypeInitialMargin: wasm.marginCallTypeInitialMargin,
  marginCallTypeSubstitution: wasm.marginCallTypeSubstitution,
  marginCallTypeTopUp: wasm.marginCallTypeTopUp,
  marginCallTypeVariationMarginCollect: wasm.marginCallTypeVariationMarginCollect,
  marginCallTypeVariationMarginPost: wasm.marginCallTypeVariationMarginPost,
  marginFundingCost: wasm.marginFundingCost,
  marginFundingCostCostForPeriod: wasm.marginFundingCostCostForPeriod,
  marginFundingCostSpread: wasm.marginFundingCostSpread,
  marginTenorDaily: wasm.marginTenorDaily,
  marginTenorFromStr: wasm.marginTenorFromStr,
  marginTenorMonthly: wasm.marginTenorMonthly,
  marginTenorOnDemand: wasm.marginTenorOnDemand,
  marginTenorWeekly: wasm.marginTenorWeekly,
  marginUtilization: wasm.marginUtilization,
  marginUtilizationIsAdequate: wasm.marginUtilizationIsAdequate,
  marginUtilizationRatio: wasm.marginUtilizationRatio,
  marginUtilizationShortfall: wasm.marginUtilizationShortfall,
  nettingSetIdBilateral: wasm.nettingSetIdBilateral,
  nettingSetIdCleared: wasm.nettingSetIdCleared,
  saCcrNettingSetConfigMargined: wasm.saCcrNettingSetConfigMargined,
  saCcrNettingSetConfigUnmargined: wasm.saCcrNettingSetConfigUnmargined,
  saCcrNettingSetConfigValidate: wasm.saCcrNettingSetConfigValidate,
  saccrEad: wasm.saccrEad,
  vmResultNetMargin: wasm.vmResultNetMargin,
  vmResultRequiresCall: wasm.vmResultRequiresCall,
  schema,
};
