//! QuantLib parity tests for volatility models.
//!
//! These tests validate finstack-core volatility model implementations against
//! externally generated reference values pinned in
//! `data/vol_models_quantlib.json` (generated by `data/gen_vol_golden.py`,
//! QuantLib 1.42.1). Covered models:
//!
//! - Black-76 (undiscounted, unit annuity) + implied-vol round-trip
//! - Black-Scholes-Merton spot prices with continuous dividend yield
//! - Bachelier (normal) prices, including negative forwards/strikes,
//!   + implied normal vol round-trip
//! - SABR Hagan lognormal vol (beta in {0, 0.5, 1}, shifted SABR) and
//!   Hagan normal vol
//! - Heston (Gatheral / little-trap formulation) European prices
//! - SVI total variance / implied vol (mpmath 50-digit reference)
//! - Rough Heston classical limit: H = 0.499 vs classical Heston price
//!
//! # Convention mapping
//!
//! - QuantLib `blackFormula(type, strike, forward, stdDev, discount)` takes
//!   `stdDev = sigma * sqrt(T)`; fixtures use `discount = 1.0` so expected
//!   Black-76/Bachelier prices are undiscounted, matching the unit-annuity
//!   convention of [`black_call`]/[`bachelier_call`]. The fixture records the
//!   discount factor `exp(-r*T)` separately for Black-76 to document the
//!   mapping.
//! - BSM expected prices are discounted spot-based values; QuantLib computed
//!   them via `blackFormula` on `F = S*exp((r-q)T)` with `discount =
//!   exp(-rT)`, which is identical to the BSM spot formula implemented by
//!   [`black_scholes_spot_call`].
//! - QuantLib `sabrVolatility(strike, forward, T, alpha, beta, nu, rho)`
//!   swaps the (nu, rho) order relative to [`SabrParams::new`].
//!
//! # Tolerances
//!
//! - Closed forms (Black-76, BSM, Bachelier): 5e-9 relative. Adjudicated
//!   against 50-digit mpmath: finstack's `norm_cdf` (statrs erfc) carries up
//!   to ~1e-9 relative price error at moderate moneyness, while QuantLib's
//!   CDF carries up to ~2.5e-9 relative error on far-OTM tail prices (where
//!   finstack is the more accurate side). See `data/gen_vol_golden.py`.
//! - SABR: 1e-10 relative (same Hagan 2002 formula as QuantLib).
//! - Heston: 1e-6 relative (different quadrature: composite Gauss-Legendre
//!   here vs adaptive Gauss-Lobatto in QuantLib). Four T=1 cases are pinned
//!   but marked `skip: true` in the fixture: the fixed Gauss-Legendre grid
//!   carries ~2.6e-6 (vov 0.3, rho -0.5) to ~7.5e-5 (vov 0.5, rho -0.9)
//!   absolute error at short maturity; T=5 and T=10 pass at 1e-6.
//! - Implied vol round-trip: 1e-8 absolute on the recovered vol.
//! - SVI: 1e-12 relative (exact formula vs 50-digit mpmath).
//! - Rough Heston classical limit: 0.5% relative (H = 0.499 approximates the
//!   H -> 0.5 classical limit; fractional Riccati discretisation error).
//!
//! # References
//!
//! - QuantLib 1.42.1, <https://www.quantlib.org/>
//! - Hagan, P. et al. (2002). "Managing Smile Risk." *Wilmott Magazine*.
//! - Albrecher, H., Mayer, P., Schoutens, W., & Tistaert, J. (2007).
//!   "The little Heston trap." *Wilmott Magazine*, 83-92.
//! - Gatheral, J. (2004). "A parsimonious arbitrage-free implied volatility
//!   parameterization." Global Derivatives.
//! - El Euch, O., & Rosenbaum, M. (2019). "The characteristic function of
//!   rough Heston models." *Mathematical Finance*, 29(1), 3-38.

use finstack_core::math::volatility::heston::HestonParams;
use finstack_core::math::volatility::rough_heston::RoughHestonFourierParams;
use finstack_core::math::volatility::sabr::SabrParams;
use finstack_core::math::volatility::svi::SviParams;
use finstack_core::math::volatility::{
    bachelier_call, bachelier_put, black_call, black_put, black_scholes_spot_call,
    black_scholes_spot_put, implied_vol_bachelier, implied_vol_black,
};
use finstack_test_utils::golden::{load_suite_from_path, GoldenSuite};
use serde::Deserialize;

/// Helper macro to get the path to golden test data.
macro_rules! golden_path {
    ($file:expr) => {
        concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/", $file)
    };
}

/// Expected call/put price pair with relative tolerance.
#[derive(Debug, Deserialize)]
struct PricePair {
    call: f64,
    put: f64,
    tolerance_rel: f64,
}

/// Expected implied volatility with relative tolerance.
#[derive(Debug, Deserialize)]
struct VolExpected {
    vol: f64,
    tolerance_rel: f64,
}

/// Expected SVI outputs with relative tolerance.
#[derive(Debug, Deserialize)]
struct SviExpected {
    total_variance: f64,
    implied_vol: f64,
    tolerance_rel: f64,
}

/// Expected rough-Heston classical-limit call price.
#[derive(Debug, Deserialize)]
struct CallExpected {
    call: f64,
    tolerance_rel: f64,
}

/// One golden case, tagged by model section.
#[derive(Debug, Deserialize)]
#[serde(tag = "model", rename_all = "snake_case")]
#[allow(clippy::large_enum_variant)] // test fixture; readability over size
enum VolCase {
    Black76 {
        id: String,
        forward: f64,
        strike: f64,
        sigma: f64,
        t: f64,
        /// Recorded for provenance; prices are undiscounted (unit annuity).
        #[allow(dead_code)]
        rate: f64,
        discount_factor: f64,
        expected: PricePair,
        #[serde(default)]
        skip: bool,
    },
    Bsm {
        id: String,
        spot: f64,
        strike: f64,
        rate: f64,
        dividend_yield: f64,
        sigma: f64,
        t: f64,
        expected: PricePair,
        #[serde(default)]
        skip: bool,
    },
    Bachelier {
        id: String,
        forward: f64,
        strike: f64,
        sigma_n: f64,
        t: f64,
        expected: PricePair,
        #[serde(default)]
        skip: bool,
    },
    SabrLognormal {
        id: String,
        forward: f64,
        strike: f64,
        t: f64,
        alpha: f64,
        beta: f64,
        rho: f64,
        nu: f64,
        #[serde(default)]
        shift: Option<f64>,
        expected: VolExpected,
        #[serde(default)]
        skip: bool,
    },
    SabrNormal {
        id: String,
        forward: f64,
        strike: f64,
        t: f64,
        alpha: f64,
        beta: f64,
        rho: f64,
        nu: f64,
        expected: VolExpected,
        #[serde(default)]
        skip: bool,
    },
    Heston {
        id: String,
        spot: f64,
        strike: f64,
        rate: f64,
        dividend_yield: f64,
        t: f64,
        v0: f64,
        kappa: f64,
        theta: f64,
        sigma: f64,
        rho: f64,
        expected: PricePair,
        #[serde(default)]
        skip: bool,
    },
    Svi {
        id: String,
        a: f64,
        b: f64,
        rho: f64,
        m: f64,
        sigma: f64,
        t: f64,
        k: f64,
        expected: SviExpected,
        #[serde(default)]
        skip: bool,
    },
    RoughHestonClassical {
        id: String,
        spot: f64,
        strike: f64,
        rate: f64,
        dividend_yield: f64,
        t: f64,
        v0: f64,
        kappa: f64,
        theta: f64,
        sigma: f64,
        rho: f64,
        hurst: f64,
        expected: CallExpected,
        #[serde(default)]
        skip: bool,
    },
}

/// Relative-error check; for near-zero expected values falls back to an
/// absolute comparison at the same tolerance.
fn check_rel(
    failures: &mut Vec<String>,
    id: &str,
    label: &str,
    actual: f64,
    expected: f64,
    tol: f64,
) {
    let err = if expected.abs() < 1e-15 {
        actual.abs()
    } else {
        ((actual - expected) / expected).abs()
    };
    // NaN-aware: a NaN error must register as a failure.
    if err.is_nan() || err > tol {
        failures.push(format!(
            "[{id}] {label}: expected {expected:.15e}, got {actual:.15e} (rel err {err:.3e} > {tol:.1e})"
        ));
    }
}

fn load_vol_suite() -> GoldenSuite<VolCase> {
    let path = golden_path!("data/vol_models_quantlib.json");
    let suite: GoldenSuite<VolCase> =
        load_suite_from_path(path).expect("Failed to load vol models golden suite");
    assert_eq!(suite.meta.suite_id, "vol_models_quantlib_parity");
    assert!(!suite.cases.is_empty(), "Suite should have test cases");
    suite
}

#[test]
fn test_vol_models_quantlib_parity() {
    let suite = load_vol_suite();
    let mut failures: Vec<String> = Vec::new();
    let mut counts = std::collections::BTreeMap::<&'static str, usize>::new();

    for case in &suite.cases {
        match case {
            VolCase::Black76 {
                id,
                forward,
                strike,
                sigma,
                t,
                discount_factor,
                expected,
                skip,
                ..
            } => {
                if *skip {
                    continue;
                }
                *counts.entry("black76").or_default() += 1;
                let call = black_call(*forward, *strike, *sigma, *t);
                let put = black_put(*forward, *strike, *sigma, *t);
                let tol = expected.tolerance_rel;
                check_rel(&mut failures, id, "call", call, expected.call, tol);
                check_rel(&mut failures, id, "put", put, expected.put, tol);
                // Convention mapping check: discounted premium = df * undiscounted.
                check_rel(
                    &mut failures,
                    id,
                    "discounted_call",
                    discount_factor * call,
                    discount_factor * expected.call,
                    tol,
                );
            }
            VolCase::Bsm {
                id,
                spot,
                strike,
                rate,
                dividend_yield,
                sigma,
                t,
                expected,
                skip,
            } => {
                if *skip {
                    continue;
                }
                *counts.entry("bsm").or_default() += 1;
                let call =
                    black_scholes_spot_call(*spot, *strike, *rate, *dividend_yield, *sigma, *t);
                let put =
                    black_scholes_spot_put(*spot, *strike, *rate, *dividend_yield, *sigma, *t);
                let tol = expected.tolerance_rel;
                check_rel(&mut failures, id, "call", call, expected.call, tol);
                check_rel(&mut failures, id, "put", put, expected.put, tol);
            }
            VolCase::Bachelier {
                id,
                forward,
                strike,
                sigma_n,
                t,
                expected,
                skip,
            } => {
                if *skip {
                    continue;
                }
                *counts.entry("bachelier").or_default() += 1;
                let call = bachelier_call(*forward, *strike, *sigma_n, *t);
                let put = bachelier_put(*forward, *strike, *sigma_n, *t);
                let tol = expected.tolerance_rel;
                check_rel(&mut failures, id, "call", call, expected.call, tol);
                check_rel(&mut failures, id, "put", put, expected.put, tol);
            }
            VolCase::SabrLognormal {
                id,
                forward,
                strike,
                t,
                alpha,
                beta,
                rho,
                nu,
                shift,
                expected,
                skip,
            } => {
                if *skip {
                    continue;
                }
                *counts.entry("sabr_lognormal").or_default() += 1;
                let mut params =
                    SabrParams::new(*alpha, *beta, *rho, *nu).expect("valid SABR params");
                if let Some(s) = shift {
                    params = params.with_shift(*s);
                }
                let vol = params.implied_vol_lognormal(*forward, *strike, *t);
                check_rel(
                    &mut failures,
                    id,
                    "vol",
                    vol,
                    expected.vol,
                    expected.tolerance_rel,
                );
            }
            VolCase::SabrNormal {
                id,
                forward,
                strike,
                t,
                alpha,
                beta,
                rho,
                nu,
                expected,
                skip,
            } => {
                if *skip {
                    continue;
                }
                *counts.entry("sabr_normal").or_default() += 1;
                let params = SabrParams::new(*alpha, *beta, *rho, *nu).expect("valid SABR params");
                let vol = params.implied_vol_normal(*forward, *strike, *t);
                check_rel(
                    &mut failures,
                    id,
                    "vol",
                    vol,
                    expected.vol,
                    expected.tolerance_rel,
                );
            }
            VolCase::Heston {
                id,
                spot,
                strike,
                rate,
                dividend_yield,
                t,
                v0,
                kappa,
                theta,
                sigma,
                rho,
                expected,
                skip,
            } => {
                if *skip {
                    continue;
                }
                *counts.entry("heston").or_default() += 1;
                let params =
                    HestonParams::new(*v0, *kappa, *theta, *sigma, *rho).expect("valid Heston");
                let call = params.price_european(*spot, *strike, *rate, *dividend_yield, *t, true);
                let put = params.price_european(*spot, *strike, *rate, *dividend_yield, *t, false);
                let tol = expected.tolerance_rel;
                check_rel(&mut failures, id, "call", call, expected.call, tol);
                check_rel(&mut failures, id, "put", put, expected.put, tol);
            }
            VolCase::Svi {
                id,
                a,
                b,
                rho,
                m,
                sigma,
                t,
                k,
                expected,
                skip,
            } => {
                if *skip {
                    continue;
                }
                *counts.entry("svi").or_default() += 1;
                let params: SviParams = serde_json::from_value(serde_json::json!({
                    "a": a, "b": b, "rho": rho, "m": m, "sigma": sigma
                }))
                .expect("valid SVI params");
                let tol = expected.tolerance_rel;
                check_rel(
                    &mut failures,
                    id,
                    "total_variance",
                    params.total_variance(*k),
                    expected.total_variance,
                    tol,
                );
                check_rel(
                    &mut failures,
                    id,
                    "implied_vol",
                    params.implied_vol(*k, *t),
                    expected.implied_vol,
                    tol,
                );
            }
            VolCase::RoughHestonClassical {
                id,
                spot,
                strike,
                rate,
                dividend_yield,
                t,
                v0,
                kappa,
                theta,
                sigma,
                rho,
                hurst,
                expected,
                skip,
            } => {
                if *skip {
                    continue;
                }
                *counts.entry("rough_heston_classical").or_default() += 1;
                let params =
                    RoughHestonFourierParams::new(*v0, *kappa, *theta, *sigma, *rho, *hurst)
                        .expect("valid rough Heston params");
                let call = params.price_european(*spot, *strike, *rate, *dividend_yield, *t, true);
                check_rel(
                    &mut failures,
                    id,
                    "call",
                    call,
                    expected.call,
                    expected.tolerance_rel,
                );
            }
        }
    }

    // Guard against silently empty sections (e.g. a renamed tag).
    for section in [
        "black76",
        "bsm",
        "bachelier",
        "sabr_lognormal",
        "sabr_normal",
        "heston",
        "svi",
        "rough_heston_classical",
    ] {
        assert!(
            counts.get(section).copied().unwrap_or(0) > 0,
            "No cases executed for section '{section}'"
        );
    }

    assert!(
        failures.is_empty(),
        "QuantLib vol model parity failures ({}):\n{}",
        failures.len(),
        failures.join("\n")
    )
}

/// Implied-vol round-trip: invert the Black-76 and Bachelier fixture prices
/// and recover the input volatilities within 1e-8 absolute.
///
/// Cases whose option price is at intrinsic to machine precision (deep
/// ITM/OTM, short expiry) are excluded from the round-trip because the
/// price-vol mapping is non-invertible there; the threshold is documented
/// inline.
#[test]
fn test_implied_vol_round_trip_quantlib_prices() {
    /// Absolute tolerance on the recovered volatility.
    const ROUND_TRIP_TOL: f64 = 1e-8;
    /// Minimum time value (relative to forward/strike scale) for a price to
    /// be considered invertible.
    const MIN_TIME_VALUE_REL: f64 = 1e-12;

    let suite = load_vol_suite();
    let mut failures: Vec<String> = Vec::new();
    let mut round_trips = 0usize;

    let round_trip = |id: &str,
                      label: &str,
                      price: f64,
                      intrinsic: f64,
                      scale: f64,
                      recovered: finstack_core::Result<f64>,
                      input_vol: f64,
                      failures: &mut Vec<String>| {
        if price - intrinsic <= MIN_TIME_VALUE_REL * scale {
            return false; // non-invertible: price at intrinsic
        }
        match recovered {
            Ok(vol) => {
                if (vol - input_vol).abs() > ROUND_TRIP_TOL {
                    failures.push(format!(
                        "[{id}] {label}: implied vol {vol:.12} vs input {input_vol:.12} \
                         (abs err {:.3e} > {ROUND_TRIP_TOL:.1e})",
                        (vol - input_vol).abs()
                    ));
                }
            }
            Err(e) => failures.push(format!("[{id}] {label}: inversion failed: {e}")),
        }
        true
    };

    for case in &suite.cases {
        match case {
            VolCase::Black76 {
                id,
                forward,
                strike,
                sigma,
                t,
                expected,
                skip,
                ..
            } => {
                if *skip {
                    continue;
                }
                let scale = forward.max(*strike);
                let call_intrinsic = (forward - strike).max(0.0);
                let put_intrinsic = (strike - forward).max(0.0);
                if round_trip(
                    id,
                    "call",
                    expected.call,
                    call_intrinsic,
                    scale,
                    implied_vol_black(expected.call, *forward, *strike, *t, true),
                    *sigma,
                    &mut failures,
                ) {
                    round_trips += 1;
                }
                if round_trip(
                    id,
                    "put",
                    expected.put,
                    put_intrinsic,
                    scale,
                    implied_vol_black(expected.put, *forward, *strike, *t, false),
                    *sigma,
                    &mut failures,
                ) {
                    round_trips += 1;
                }
            }
            VolCase::Bachelier {
                id,
                forward,
                strike,
                sigma_n,
                t,
                expected,
                skip,
            } => {
                if *skip {
                    continue;
                }
                let scale = forward.abs().max(strike.abs()).max(1e-10);
                let call_intrinsic = (forward - strike).max(0.0);
                let put_intrinsic = (strike - forward).max(0.0);
                // Normal vols span very different scales (0.005 vs 20); use a
                // scale-aware tolerance: 1e-8 * max(sigma_n, 1).
                let tol_scale = sigma_n.max(1.0);
                if expected.call - call_intrinsic > MIN_TIME_VALUE_REL * scale {
                    round_trips += 1;
                    match implied_vol_bachelier(expected.call, *forward, *strike, *t, true) {
                        Ok(vol) => {
                            if (vol - sigma_n).abs() > ROUND_TRIP_TOL * tol_scale {
                                failures.push(format!(
                                    "[{id}] call: implied normal vol {vol:.12} vs input {sigma_n:.12}"
                                ));
                            }
                        }
                        Err(e) => failures.push(format!("[{id}] call: inversion failed: {e}")),
                    }
                }
                if expected.put - put_intrinsic > MIN_TIME_VALUE_REL * scale {
                    round_trips += 1;
                    match implied_vol_bachelier(expected.put, *forward, *strike, *t, false) {
                        Ok(vol) => {
                            if (vol - sigma_n).abs() > ROUND_TRIP_TOL * tol_scale {
                                failures.push(format!(
                                    "[{id}] put: implied normal vol {vol:.12} vs input {sigma_n:.12}"
                                ));
                            }
                        }
                        Err(e) => failures.push(format!("[{id}] put: inversion failed: {e}")),
                    }
                }
            }
            _ => {}
        }
    }

    assert!(
        round_trips >= 50,
        "Expected at least 50 invertible round-trip cases, got {round_trips}"
    );

    assert!(
        failures.is_empty(),
        "Implied vol round-trip failures ({}):\n{}",
        failures.len(),
        failures.join("\n")
    )
}
