//! Euler discretization for the rBergomi process.
//!
//! Operates in log-spot for numerical stability. The variance is reconstructed
//! from the forward variance curve and the accumulated Riemann-Liouville
//! Volterra path at each step.
//!
//! # Noise Layout
//!
//! The discretization expects `z` with three entries:
//!
//! - `z[0]` — independent standard normal for the uncorrelated spot component
//! - `z[1]` — increment `ΔỸ` of the Riemann-Liouville Volterra process for the
//!   current step, pre-generated by the engine's fractional noise integration
//!   from a [`RiemannLiouvilleVolterra`](crate::rng::volterra::RiemannLiouvilleVolterra)
//!   generator
//! - `z[2]` — the **unit-variance driving Brownian normal** `Z̃_k` for the
//!   current step, i.e. `ΔW̃_k / √dt`, where `W̃` is the Brownian motion that
//!   drives the Volterra process. Also supplied by the fractional noise
//!   integration.
//!
//! # Spot–Vol Correlation
//!
//! In the Bayer-Friz-Gatheral rBergomi model the spot Brownian motion `W` is
//! correlated with the Volterra driver `W̃` by `dW·dW̃ = ρ dt`. The correlated
//! spot increment is therefore built directly from the driving normal `Z̃_k`:
//!
//! ```text
//! Z_corr = ρ Z̃ + √(1 − ρ²) Z_indep
//! dW_spot = Z_corr √dt
//! ```
//!
//! This is exact: `Z̃` is genuinely unit-variance (`ΔW̃_k = √dt · Z̃_k`), unlike
//! the Volterra *increment* `ΔỸ`, whose variance is neither `dt^{2H}` nor
//! stationary. Correlating against `Z̃` is the correct rBergomi spot–vol
//! coupling (Bayer-Friz-Gatheral 2016; McCrickerd & Pakkanen 2018).
//!
//! # Work Buffer
//!
//! `work[0]` stores the running accumulated Riemann-Liouville Volterra process
//! `Ỹ(t) = √(2H)·∫₀ᵗ(t−s)^{H−½}dW_s`. Because the
//! [`RiemannLiouvilleVolterra`](crate::rng::volterra::RiemannLiouvilleVolterra)
//! generator emits increments `ΔỸ_k` whose running sum reconstructs the level
//! `Ỹ_{t_k}`, accumulating `work[0] += ΔỸ` recovers the Volterra process.
//! The engine must zero the work buffer before each new path (see
//! [`simulate_path_fractional`](crate::engine_fractional::simulate_path_fractional)).
//!
//! # References
//!
//! - Bayer, C., Friz, P., & Gatheral, J. (2016). "Pricing under rough
//!   volatility." *Quantitative Finance*, 16(6), 887–904.
//! - Bennedsen, M., Lunde, A. & Pakkanen, M. S. (2017). "Hybrid scheme for
//!   Brownian semistationary processes." *Finance and Stochastics*, 21(4),
//!   931–965.
//! - McCrickerd, R. & Pakkanen, M. S. (2018). "Turbocharging Monte Carlo
//!   pricing for the rough Bergomi model." *Quantitative Finance*, 18(11),
//!   1877–1886.

use super::super::process::rough_bergomi::RoughBergomiProcess;
use super::super::traits::Discretization;
use finstack_quant_core::math::fractional::HurstExponent;

/// Euler discretization for the rBergomi process.
///
/// This scheme reconstructs the variance from the forward variance curve and
/// the accumulated Riemann-Liouville Volterra path at each time step. It is
/// the only supported discretization for [`RoughBergomiProcess`] because the
/// non-Markovian variance dynamics cannot be expressed through the standard
/// `drift`/`diffusion` interface.
///
/// See the [module-level documentation](self) for details on noise layout,
/// correlation handling, and the work buffer.
#[derive(Debug, Clone)]
pub struct RoughBergomiEuler {
    /// Hurst exponent of the Riemann-Liouville Volterra driver.
    hurst: HurstExponent,
}

impl RoughBergomiEuler {
    /// Create a new rBergomi Euler discretization.
    ///
    /// # Arguments
    ///
    /// * `hurst` - Validated Hurst exponent, must match the process.
    pub fn new(hurst: HurstExponent) -> Self {
        Self { hurst }
    }

    /// Return the stored Hurst exponent.
    pub fn hurst(&self) -> HurstExponent {
        self.hurst
    }
}

impl Discretization<RoughBergomiProcess> for RoughBergomiEuler {
    fn step(
        &self,
        process: &RoughBergomiProcess,
        t: f64,
        dt: f64,
        x: &mut [f64],
        z: &[f64],
        work: &mut [f64],
    ) {
        let params = process.params();
        let h = params.hurst.value();
        let eta = params.eta;
        let rho = params.rho;

        let z_indep = z[0]; // Independent standard normal (uncorrelated spot)
        let d_y = z[1]; // RL Volterra increment ΔỸ for this step (pre-generated)
        let z_drive = z[2]; // Unit-variance driving Brownian normal Z̃ = ΔW̃/√dt

        // Reconstruct the LEFT-endpoint variance V_t from the Volterra process
        // accumulated *up to* time t (work[0] = Ỹ_t, before this step's ΔỸ):
        //   V_t = ξ₀(t) exp(η Ỹ_t − ½ η² t^{2H})
        //
        // Using the left-endpoint variance is essential for the forward-Euler
        // scheme to preserve the spot martingale: V_t is built from driving
        // normals strictly before this step, so it is independent of this
        // step's shock Z̃_k. Using the *end*-of-step variance V_{t+dt} (which
        // depends on ΔỸ_k, hence on Z̃_k) would correlate the variance with the
        // step's own shock and bias E[S_T] away from the forward.
        // Var(Ỹ_t) = t^{2H} for the √(2H)-normalised RL Volterra process, so
        // the convexity correction at time t is ½η²t^{2H}.
        let two_h = 2.0 * h;
        let y_t = work[0];
        let exponent = eta * y_t - 0.5 * eta * eta * t.powf(two_h);
        let raw_variance = params.xi.value(t) * exponent.exp();
        let v_t = if raw_variance.is_finite() {
            raw_variance.max(0.0)
        } else {
            raw_variance
        };

        // Correlate spot noise with the Volterra driver. The Bayer-Friz-Gatheral
        // coupling is dW·dW̃ = ρ dt, so the correlated spot normal is built from
        // the unit-variance driving normal Z̃ — exact, with no dt^H rescaling.
        let z_correlated = rho * z_drive + (1.0 - rho * rho).max(0.0).sqrt() * z_indep;

        // Log-spot update over [t, t+dt] with the left-endpoint variance:
        //   S_{t+dt} = S_t exp((r − q − ½V_t) dt + √V_t √dt Z_corr)
        let drift = (params.r - params.q - 0.5 * v_t) * dt;
        let diffusion = v_t.sqrt() * dt.sqrt() * z_correlated;
        x[0] *= (drift + diffusion).exp();

        // Accumulate the Volterra process for the next step:
        //   Ỹ_{t+dt} = Ỹ_t + ΔỸ,  with Ỹ_t = √(2H)∫₀ᵗ(t−s)^{H−½}dW̃_s.
        work[0] += d_y;
    }

    fn work_size(&self, _process: &RoughBergomiProcess) -> usize {
        1 // work[0] = accumulated RL Volterra process Ỹ(t)
    }
}

#[cfg(test)]
mod tests {
    use super::super::super::process::rough_bergomi::{RoughBergomiParams, RoughBergomiProcess};
    use super::*;
    use finstack_quant_core::market_data::term_structures::ForwardVarianceCurve;
    use finstack_quant_core::math::fractional::HurstExponent;

    fn make_process() -> RoughBergomiProcess {
        let xi = ForwardVarianceCurve::flat(0.04).expect("valid flat curve");
        let hurst = HurstExponent::new(0.1).expect("valid hurst");
        let params = RoughBergomiParams::new(0.05, 0.02, hurst, 1.9, -0.9, xi).expect("valid");
        RoughBergomiProcess::new(params)
    }

    #[test]
    fn test_single_step_zero_shocks() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![100.0];
        let z = vec![0.0, 0.0, 0.0]; // No shocks: indep, ΔỸ, driving normal
        let mut work = vec![0.0];

        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

        // Spot should remain close to initial with small drift
        assert!(x[0] > 0.0, "Spot must remain positive");
        assert!(
            (x[0] - 100.0).abs() < 5.0,
            "Spot should stay near 100 with zero shocks: got {}",
            x[0]
        );
    }

    #[test]
    fn test_single_step_deterministic() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));
        let params = process.params();

        let s0 = 100.0;
        let dt = 0.01_f64;
        // Start mid-grid so the left-endpoint variance uses a non-zero time
        // and a non-zero accumulated Volterra level.
        let t = 0.5_f64;
        let h = params.hurst.value();
        let eta = params.eta;
        let r = params.r;
        let q = params.q;
        let rho = params.rho;

        let z_indep = 0.5;
        let d_y = 0.02; // RL Volterra increment ΔỸ for this step
        let z_drive = -0.3; // unit-variance driving Brownian normal Z̃
        let y_t = 0.03_f64; // Volterra level Ỹ_t accumulated before this step

        let mut x = vec![s0];
        let z = vec![z_indep, d_y, z_drive];
        let mut work = vec![y_t];

        disc.step(&process, t, dt, &mut x, &z, &mut work);

        // Manually compute expected result: the spot step uses the LEFT-endpoint
        // variance V_t built from Ỹ_t (before ΔỸ) with convexity at time t.
        let two_h = 2.0 * h;
        let exponent = eta * y_t - 0.5 * eta * eta * t.powf(two_h);
        let v = (params.xi.value(t) * exponent.exp()).max(0.0);

        // Spot–vol correlation uses the driving normal directly (no dt^H scale).
        let z_corr = rho * z_drive + (1.0 - rho * rho).max(0.0).sqrt() * z_indep;

        let drift = (r - q - 0.5 * v) * dt;
        let diff = v.sqrt() * dt.sqrt() * z_corr;
        let expected = s0 * (drift + diff).exp();

        assert!(
            (x[0] - expected).abs() < 1e-12,
            "Single step mismatch: got {}, expected {}",
            x[0],
            expected
        );
        // The Volterra accumulator advances to Ỹ_{t+dt} = Ỹ_t + ΔỸ.
        assert!(
            (work[0] - (y_t + d_y)).abs() < 1e-15,
            "work[0] should accumulate to Ỹ_t + ΔỸ"
        );
    }

    #[test]
    fn test_variance_reconstruction() {
        let xi = ForwardVarianceCurve::flat(0.04).expect("valid flat curve");
        let h = 0.1_f64;
        let eta = 1.9_f64;
        let t = 0.5_f64;
        let w_h = 0.03_f64;

        // V_t = ξ₀(t) exp(η Ỹ_t − ½ η² t^{2H})
        let two_h = 2.0 * h;
        let exponent = eta * w_h - 0.5 * eta * eta * t.powf(two_h);
        let v = xi.value(t) * exponent.exp();

        // With flat ξ₀ = 0.04 and small w_h, variance should be positive
        assert!(v > 0.0, "Reconstructed variance should be positive: {v}");

        // With zero accumulation, variance should equal ξ₀(t) * exp(-½η²t^{2H})
        let exponent_zero = -0.5 * eta * eta * t.powf(two_h);
        let v_zero = xi.value(t) * exponent_zero.exp();
        assert!(v_zero > 0.0);
        assert!(
            v_zero < 0.04,
            "Variance should be below flat level due to convexity correction"
        );
    }

    #[test]
    fn test_work_buffer_reset_across_paths() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        let mut x = vec![100.0];
        let z = vec![0.0, 0.05, 0.0]; // Non-zero RL Volterra increment ΔỸ
        let mut work = vec![0.0];

        // Simulate a few steps of path 1
        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);
        disc.step(&process, 0.01, 0.01, &mut x, &z, &mut work);

        let w_h_after_path1 = work[0];
        assert!(
            w_h_after_path1.abs() > 1e-15,
            "Work buffer should accumulate RL Volterra increments"
        );

        // Start path 2 — engine zeros work buffer before each path
        x[0] = 100.0;
        work[0] = 0.0;
        disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

        // After a single step from t=0, work[0] should be exactly the single
        // RL Volterra increment (accumulator was zeroed by engine before path)
        assert!(
            (work[0] - 0.05).abs() < 1e-15,
            "Work buffer should reset at path start: got {}",
            work[0]
        );
    }

    #[test]
    fn test_spot_stays_positive_under_large_shocks() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        for &z_val in &[-3.0, -2.0, 2.0, 3.0] {
            let mut x = vec![100.0];
            // indep spot shock, RL Volterra increment, driving normal.
            let z = vec![z_val, z_val * 0.1, z_val];
            let mut work = vec![0.0];

            disc.step(&process, 0.0, 0.01, &mut x, &z, &mut work);

            assert!(
                x[0] > 0.0,
                "Spot must remain positive with z={z_val}: got {}",
                x[0]
            );
        }
    }

    #[test]
    fn test_work_size() {
        let process = make_process();
        let disc = RoughBergomiEuler::new(HurstExponent::new(0.1).expect("valid hurst"));

        assert_eq!(disc.work_size(&process), 1);
    }

    // -- rBergomi spot martingale property ---------------------------------

    /// Spot martingale test: with `r = q = 0` the discounted spot
    /// `E[S_T] = S_0` must hold under the rBergomi dynamics, even with a large
    /// vol-of-vol `η` and a strong leverage `ρ`.
    ///
    /// This is the guard for the forward-Euler **left-endpoint variance**: the
    /// step over `[t_k, t_{k+1}]` must use the variance `V_{t_k}` built from
    /// the Volterra level *before* this step's increment, so `V_{t_k}` is
    /// independent of the step's own driving shock `Z̃_k`. Using the
    /// end-of-step variance `V_{t_{k+1}}` (which depends on `ΔỸ_k`, hence on
    /// `Z̃_k`) correlates the variance with the step shock and biases `E[S_T]`
    /// well below the forward — this test fails hard on that bug (observed
    /// `E[S_T] ≈ 61` instead of `100` at `η = 1.9`).
    #[test]
    #[ignore = "slow: covered by mise rust-test-slow"]
    fn rbergomi_spot_is_a_martingale() {
        use super::super::super::rng::fbm::FractionalNoiseGenerator;
        use super::super::super::rng::philox::PhiloxRng;
        use super::super::super::rng::volterra::RiemannLiouvilleVolterra;
        use super::super::super::traits::RandomStream;

        let t_end = 1.0_f64;
        let n = 100usize;
        let s0 = 100.0_f64;
        let xi0 = 0.04_f64;

        // Stress the property: large vol-of-vol and strong negative leverage.
        for &(h, eta, rho) in &[(0.1_f64, 1.9_f64, -0.9_f64), (0.07, 2.5, -0.7)] {
            let xi = ForwardVarianceCurve::flat(xi0).expect("valid flat curve");
            let hurst = HurstExponent::new(h).expect("valid hurst");
            // r = q = 0 ⇒ the spot itself must be a martingale.
            let params =
                RoughBergomiParams::new(0.0, 0.0, hurst, eta, rho, xi).expect("valid params");
            let process = RoughBergomiProcess::new(params);
            let disc = RoughBergomiEuler::new(hurst);

            let gen = RiemannLiouvilleVolterra::new(t_end, n, h).expect("valid generator");
            let dt = gen.dt();
            let mut rng = PhiloxRng::new(424242);

            let num_paths = 200_000usize;
            let mut vol_normals = vec![0.0; 2 * n];
            let mut spot_normals = vec![0.0; n];
            let mut increments = vec![0.0; n];
            let mut driving = vec![0.0; n];

            let mut sum_st = 0.0;
            for _ in 0..num_paths {
                rng.fill_std_normals(&mut vol_normals);
                rng.fill_std_normals(&mut spot_normals);
                gen.generate(&vol_normals, &mut increments);
                gen.driving_normals_into(&vol_normals, &mut driving);

                let mut x = [s0];
                let mut work = [0.0];
                for k in 0..n {
                    let t = k as f64 * dt;
                    let z = [spot_normals[k], increments[k], driving[k]];
                    disc.step(&process, t, dt, &mut x, &z, &mut work);
                }
                sum_st += x[0];
            }
            let mean_st = sum_st / num_paths as f64;
            let rel = (mean_st - s0).abs() / s0;
            // 1.5% band: MC standard error of S_T plus the small forward-Euler
            // discretization bias. The end-of-step-variance bug would land
            // E[S_T] tens of percent low — far outside this band.
            assert!(
                rel < 1.5e-2,
                "rBergomi spot must be a martingale (H={h}, η={eta}, ρ={rho}): \
                 E[S_T]={mean_st} should be ≈ S_0={s0}, rel err {rel}"
            );
        }
    }

    // -- rBergomi forward-variance (martingale) property -------------------

    /// Martingale test: under the rBergomi variance reconstruction
    /// `V_t = ξ₀(t)·exp(η·Ỹ_t − ½η²t^{2H})`, the forward-variance property
    /// `E[V_t] = ξ₀(t)` must hold, because `Ỹ_t` is a centred Gaussian with
    /// `Var(Ỹ_t) = t^{2H}` and so `E[exp(η·Ỹ_t − ½η²t^{2H})] = 1`.
    ///
    /// This drives the [`RiemannLiouvilleVolterra`] generator (via a seeded
    /// Philox RNG), accumulates `Ỹ_t` exactly as `RoughBergomiEuler::step`
    /// does (`work[0] += ΔỸ`), and checks the Monte Carlo mean of the variance
    /// multiplier against 1.
    ///
    /// On the *pre-fix* true-fBM driver this property happened to hold too
    /// (true fBM `B_H` also has `Var = t^{2H}`); what the fix changes is the
    /// path *autocovariance*. The genuine guard against the pre-fix behavior
    /// is [`super::super::rng::volterra::tests::variance_reconstructs_t_pow_2h`]
    /// and the kernel-weight test, which pin the RL kernel specifically. This
    /// test guards that the √(2H) normalisation and the `½η²t^{2H}` convexity
    /// term remain mutually consistent after the swap.
    #[test]
    fn rbergomi_forward_variance_is_martingale() {
        use super::super::super::rng::fbm::FractionalNoiseGenerator;
        use super::super::super::rng::philox::PhiloxRng;
        use super::super::super::rng::volterra::RiemannLiouvilleVolterra;
        use super::super::super::traits::RandomStream;

        let h = 0.1_f64;
        let eta = 1.9_f64;
        let xi0 = 0.04_f64;
        let t_end = 1.0_f64;
        let n = 100usize;

        let gen = RiemannLiouvilleVolterra::new(t_end, n, h).expect("valid generator");
        let dt = gen.dt();
        let mut rng = PhiloxRng::new(20240517);

        let num_paths = 200_000usize;
        let mut normals = vec![0.0; 2 * n];
        let mut increments = vec![0.0; n];

        // Accumulate E[V_t / ξ₀(t)] at the terminal time and at a mid-grid time.
        let mid = n / 2;
        let mut sum_mult_terminal = 0.0;
        let mut sum_mult_mid = 0.0;

        for _ in 0..num_paths {
            rng.fill_std_normals(&mut normals);
            gen.generate(&normals, &mut increments);

            // Ỹ_{t_k} = Σ_{j<k} ΔỸ_j — the same accumulation RoughBergomiEuler does.
            let mut y = 0.0;
            for (k, &d_y) in increments.iter().enumerate() {
                y += d_y;
                let t_next = (k + 1) as f64 * dt;
                let mult = (eta * y - 0.5 * eta * eta * t_next.powf(2.0 * h)).exp();
                if k + 1 == mid {
                    sum_mult_mid += mult;
                }
                if k + 1 == n {
                    sum_mult_terminal += mult;
                }
            }
        }

        let mean_mult_terminal = sum_mult_terminal / num_paths as f64;
        let mean_mult_mid = sum_mult_mid / num_paths as f64;

        // E[V_t] = ξ₀(t) ⇔ E[exp(η Ỹ_t − ½η²t^{2H})] = 1. The MC standard
        // error of the lognormal multiplier at η=1.9, H=0.1 over 2e5 paths is
        // a few ×1e-3; a 2% band is a safe statistical guard.
        assert!(
            (mean_mult_terminal - 1.0).abs() < 2e-2,
            "terminal forward-variance multiplier {mean_mult_terminal} should be ≈ 1; \
             E[V_T] = {} vs ξ₀ = {xi0}",
            xi0 * mean_mult_terminal
        );
        assert!(
            (mean_mult_mid - 1.0).abs() < 2e-2,
            "mid-grid forward-variance multiplier {mean_mult_mid} should be ≈ 1"
        );
    }

    /// rBergomi ATM-call convergence to a genuine analytic reference.
    ///
    /// As the vol-of-vol `η → 0` the rBergomi variance `V_t = ξ₀·exp(η·Ỹ_t −
    /// ½η²t^{2H})` collapses to the deterministic level `ξ₀`, so the model
    /// collapses to Black-Scholes at lognormal volatility `√ξ₀`. The ATM call
    /// price simulated through the full generator → discretization → spot path
    /// must therefore converge to the closed-form Black-Scholes price — a
    /// recognised, non-circular analytic limiting case (no golden fixture is
    /// created because a genuine independent published rBergomi price is not
    /// available; see the task report).
    ///
    /// All randomness comes from a single advancing seeded Philox stream so
    /// the Monte Carlo average is statistically valid: `2n` normals feed the
    /// RL Volterra generator, `n` feed the independent spot component.
    #[test]
    fn rbergomi_small_eta_converges_to_black_scholes_atm_call() {
        use super::super::super::rng::fbm::FractionalNoiseGenerator;
        use super::super::super::rng::philox::PhiloxRng;
        use super::super::super::rng::volterra::RiemannLiouvilleVolterra;
        use super::super::super::traits::RandomStream;
        use finstack_quant_core::math::volatility::black_scholes_spot_call;

        let h = 0.1_f64;
        let eta = 1e-3_f64; // near-zero vol-of-vol: rBergomi → Black-Scholes
        let xi0 = 0.04_f64; // flat forward variance ⇒ BS vol √ξ₀ = 20%
        let t_end = 1.0_f64;
        let n = 100usize;
        let s0 = 100.0_f64;
        let strike = 100.0_f64; // at-the-money

        let xi = ForwardVarianceCurve::flat(xi0).expect("valid flat curve");
        let hurst = HurstExponent::new(h).expect("valid hurst");
        // r = q = 0 and ρ = 0: with ρ = 0 the η→0 limit is exactly BS(√ξ₀).
        let params = RoughBergomiParams::new(0.0, 0.0, hurst, eta, 0.0, xi).expect("valid params");
        let process = RoughBergomiProcess::new(params);
        let disc = RoughBergomiEuler::new(hurst);

        let gen = RiemannLiouvilleVolterra::new(t_end, n, h).expect("valid generator");
        let dt = gen.dt();
        let mut rng = PhiloxRng::new(20240517);

        let num_paths = 200_000usize;
        let mut vol_normals = vec![0.0; 2 * n];
        let mut spot_normals = vec![0.0; n];
        let mut increments = vec![0.0; n];
        let mut driving = vec![0.0; n];

        let mut sum_payoff = 0.0;
        for _ in 0..num_paths {
            // Single advancing stream: Volterra normals then spot normals.
            rng.fill_std_normals(&mut vol_normals);
            rng.fill_std_normals(&mut spot_normals);
            gen.generate(&vol_normals, &mut increments);
            gen.driving_normals_into(&vol_normals, &mut driving);

            let mut x = [s0];
            let mut work = [0.0];
            for k in 0..n {
                let t = k as f64 * dt;
                // z = [indep spot, ΔỸ Volterra increment, driving normal Z̃].
                let z = [spot_normals[k], increments[k], driving[k]];
                disc.step(&process, t, dt, &mut x, &z, &mut work);
            }
            sum_payoff += (x[0] - strike).max(0.0);
        }
        let mc_price = sum_payoff / num_paths as f64;

        // Analytic reference: Black-Scholes ATM call at σ = √ξ₀, r = q = 0.
        let bs_price = black_scholes_spot_call(s0, strike, 0.0, 0.0, xi0.sqrt(), t_end);

        // MC standard error of an ATM call over 2e5 paths is ≈ 0.03 (price
        // units); a 3% relative band comfortably covers MC noise plus the
        // tiny residual η = 1e-3 vol-of-vol bias.
        let rel = (mc_price - bs_price).abs() / bs_price;
        assert!(
            rel < 3e-2,
            "η→0 rBergomi ATM call {mc_price} should converge to Black-Scholes \
             {bs_price} (rel err {rel})"
        );
    }
}
