import * as wasm from '../../pkg/finstack_quant_wasm.js';

export const volatility = {
  SabrCalibrator: wasm.SabrCalibrator,
  SabrModel: wasm.SabrModel,
  SabrParameters: wasm.SabrParameters,
  SabrSmile: wasm.SabrSmile,
  calibrateSvi: wasm.calibrateSvi,
  convertAtmVolatility: wasm.convertAtmVolatility,
  deltaToStrike: wasm.deltaToStrike,
  getCubeNormalVol: wasm.getCubeNormalVol,
  getCubeNormalVolClamped: wasm.getCubeNormalVolClamped,
  getCubeVol: wasm.getCubeVol,
  getCubeVolClamped: wasm.getCubeVolClamped,
  getFxDeltaPillarVols: wasm.getFxDeltaPillarVols,
  getFxDeltaVol: wasm.getFxDeltaVol,
  strikeToDelta: wasm.strikeToDelta,
  sviImpliedVol: wasm.sviImpliedVol,
  sviTotalVariance: wasm.sviTotalVariance,
  sviDurrlemanG: wasm.sviDurrlemanG,
  checkButterflyGrid: wasm.checkButterflyGrid,
  checkCalendarSpreadGrid: wasm.checkCalendarSpreadGrid,
  checkLocalVolDensityGrid: wasm.checkLocalVolDensityGrid,
  checkSurfaceGrid: wasm.checkSurfaceGrid,
  getSurfaceVol: wasm.getSurfaceVol,
  getSurfaceVolClamped: wasm.getSurfaceVolClamped,
  materializeCubeTenorSlice: wasm.materializeCubeTenorSlice,
  materializeCubeTenorSliceNormal: wasm.materializeCubeTenorSliceNormal,
  materializeCubeExpirySlice: wasm.materializeCubeExpirySlice,
  materializeCubeExpirySliceNormal: wasm.materializeCubeExpirySliceNormal,
  materializeFxDeltaSurface: wasm.materializeFxDeltaSurface,
};
