//! Shared observation schedule generation for realized-variance instruments.

use finstack_quant_core::dates::fx::ResolvedCalendarPair;
use finstack_quant_core::dates::{
    adjust, BusinessDayConvention, Date, DateExt, HolidayCalendar, ScheduleBuilder, StubKind,
    Tenor, TenorUnit,
};

/// Calendar convention for a realized-variance observation schedule.
pub(crate) enum VarianceCalendar<'a> {
    /// One named exchange or fixing-publication calendar.
    Single(&'a str),
    /// Joint base/quote currency calendars for FX observations.
    Joint { base: &'a str, quote: &'a str },
}

enum ResolvedVarianceCalendar {
    Single(&'static dyn HolidayCalendar),
    Joint(ResolvedCalendarPair),
}

impl ResolvedVarianceCalendar {
    fn resolve(spec: VarianceCalendar<'_>) -> finstack_quant_core::Result<Self> {
        match spec {
            VarianceCalendar::Single(id) => Ok(Self::Single(
                crate::cashflow::builder::calendar::resolve_calendar_strict(id)?,
            )),
            VarianceCalendar::Joint { base, quote } => Ok(Self::Joint(
                ResolvedCalendarPair::resolve(Some(base), Some(quote))?,
            )),
        }
    }

    fn adjust(&self, date: Date, bdc: BusinessDayConvention) -> finstack_quant_core::Result<Date> {
        match self {
            Self::Single(calendar) => adjust(date, bdc, *calendar),
            Self::Joint(calendars) => calendars.adjust_joint_calendar(date, bdc),
        }
    }

    fn add_business_days(&self, date: Date, count: u32) -> finstack_quant_core::Result<Date> {
        match self {
            Self::Single(calendar) => date.add_business_days(
                i32::try_from(count).map_err(|_| {
                    finstack_quant_core::InputError::InvalidTenor {
                        tenor: format!("{count}D"),
                        reason: "day count exceeds supported range".to_string(),
                    }
                })?,
                *calendar,
            ),
            Self::Joint(calendars) => calendars.add_joint_business_days(date, count),
        }
    }
}

/// Generate a strictly validated, calendar-adjusted observation schedule.
///
/// Day tenors advance in business-day steps. Week/month/year tenors are
/// generated by core [`ScheduleBuilder`] functionality, preserving the original
/// roll anchor and optional end-of-month convention. Every observation is then
/// adjusted using the contract's business-day convention.
pub(crate) fn variance_observation_dates(
    start: Date,
    maturity: Date,
    frequency: Tenor,
    bdc: BusinessDayConvention,
    end_of_month: bool,
    calendar: VarianceCalendar<'_>,
) -> finstack_quant_core::Result<Vec<Date>> {
    if frequency.count() == 0 {
        return Err(finstack_quant_core::InputError::InvalidTenor {
            tenor: format!("0{:?}", frequency.unit()),
            reason: "count must be positive".to_string(),
        }
        .into());
    }
    let calendar = ResolvedVarianceCalendar::resolve(calendar)?;

    let mut dates = if frequency.unit() == TenorUnit::Days {
        let mut dates = Vec::new();
        let mut current = calendar.adjust(start, bdc)?;
        let end = calendar.adjust(maturity, bdc)?;
        while current <= end {
            dates.push(current);
            current = calendar.add_business_days(current, frequency.count())?;
        }
        if dates.last() != Some(&end) {
            dates.push(end);
        }
        dates
    } else {
        ScheduleBuilder::new(start, maturity)?
            .frequency(frequency)
            .stub_rule(StubKind::ShortBack)
            .end_of_month(end_of_month)
            .build()?
            .dates
            .into_iter()
            .map(|date| calendar.adjust(date, bdc))
            .collect::<finstack_quant_core::Result<Vec<_>>>()?
    };

    dates.sort_unstable();
    dates.dedup();
    Ok(dates)
}

#[cfg(test)]
mod tests {
    use super::*;
    use time::macros::date;

    #[test]
    fn day_tenor_uses_holiday_calendar_and_business_endpoints() {
        let dates = variance_observation_dates(
            date!(2025 - 07 - 03),
            date!(2025 - 07 - 08),
            Tenor::daily(),
            BusinessDayConvention::Following,
            false,
            VarianceCalendar::Single("USNY"),
        )
        .expect("schedule");
        assert_eq!(
            dates,
            vec![
                date!(2025 - 07 - 03),
                date!(2025 - 07 - 07),
                date!(2025 - 07 - 08),
            ]
        );

        let weekend_end = variance_observation_dates(
            date!(2025 - 07 - 03),
            date!(2025 - 07 - 06),
            Tenor::daily(),
            BusinessDayConvention::Preceding,
            false,
            VarianceCalendar::Single("USNY"),
        )
        .expect("schedule");
        assert_eq!(weekend_end, vec![date!(2025 - 07 - 03)]);
    }

    #[test]
    fn monthly_schedule_preserves_end_of_month_anchor() {
        let dates = variance_observation_dates(
            date!(2025 - 01 - 31),
            date!(2025 - 05 - 31),
            Tenor::monthly(),
            BusinessDayConvention::Unadjusted,
            true,
            VarianceCalendar::Single("USNY"),
        )
        .expect("schedule");
        assert_eq!(dates[2], date!(2025 - 03 - 31));
    }

    #[test]
    fn zero_frequency_is_rejected_without_iteration() {
        let error = Tenor::try_new(0, TenorUnit::Days).expect_err("zero tenor");
        assert!(error.to_string().contains("count must be positive"));
    }

    #[test]
    fn unknown_calendar_is_rejected() {
        let error = variance_observation_dates(
            date!(2025 - 01 - 01),
            date!(2025 - 02 - 01),
            Tenor::daily(),
            BusinessDayConvention::Following,
            false,
            VarianceCalendar::Single("NOT-A-CALENDAR"),
        )
        .expect_err("unknown calendar");
        assert!(error.to_string().contains("NOT-A-CALENDAR"));
    }
}
