//! rough Bergomi (rBergomi) Monte Carlo pricer tests.
//!
//! These tests exercise the `EquityOptionRoughBergomiMcPricer` end-to-end
//! through the standard pricer registry. The pricer drives the variance with
//! the Riemann-Liouville Volterra process `Ỹ_t = √(2H)∫₀ᵗ(t−s)^{H−½}dW_s`
//! (Bayer-Friz-Gatheral 2016) — generated by the Bennedsen-Lunde-Pakkanen
//! hybrid scheme — not true fractional Brownian motion.
//!
//! No golden fixture is used: a genuine independent published rBergomi price
//! is not available, so the convergence test below relies on a recognised
//! analytic limiting case (η → 0 ⇒ Black-Scholes) rather than a circular
//! self-referential fixture.

use super::helpers::*;
use finstack_core::currency::Currency;
use finstack_core::math::volatility::black_scholes_spot_call;
use finstack_core::money::Money;
use finstack_valuations::instruments::PricingOptions;
use finstack_valuations::pricer::{standard_registry, ModelKey};
use time::macros::date;

/// Build an ATM market with rBergomi scalar parameters injected.
///
/// `RBERGOMI_ETA` / `RBERGOMI_HURST` / `RBERGOMI_RHO` are unitless market
/// scalars read by the pricer; the rest is a flat-vol Black-Scholes market.
fn rbergomi_market(
    as_of: finstack_core::dates::Date,
    spot: f64,
    vol: f64,
    rate: f64,
    eta: f64,
    hurst: f64,
    rho: f64,
) -> finstack_core::market_data::context::MarketContext {
    use finstack_core::market_data::scalars::MarketScalar;
    build_standard_market(as_of, spot, vol, rate, 0.0)
        .insert_price("RBERGOMI_ETA", MarketScalar::Unitless(eta))
        .insert_price("RBERGOMI_HURST", MarketScalar::Unitless(hurst))
        .insert_price("RBERGOMI_RHO", MarketScalar::Unitless(rho))
}

/// Price an ATM call through the rBergomi MC pricer with a capped path count.
fn price_rbergomi_call(
    market: &finstack_core::market_data::context::MarketContext,
    as_of: finstack_core::dates::Date,
    expiry: finstack_core::dates::Date,
    strike: f64,
    mc_paths: usize,
) -> f64 {
    let mut call = create_call(as_of, expiry, strike);
    // Cap the path count so the test runs quickly.
    call.pricing_overrides.model_config.mc_paths = Some(mc_paths);

    let registry = standard_registry();
    let result = registry
        .price_with_metrics(
            &call,
            ModelKey::MonteCarloRoughBergomi,
            market,
            as_of,
            &[],
            PricingOptions::default(),
        )
        .expect("rBergomi pricing should succeed");
    result.value.amount()
}

/// An ATM rBergomi call has a positive, sane price.
#[test]
fn rbergomi_atm_call_is_positive_and_sane() {
    let as_of = date!(2024 - 01 - 01);
    let expiry = date!(2025 - 01 - 01);
    let spot = 100.0;
    let strike = 100.0;

    let market = rbergomi_market(as_of, spot, 0.20, 0.0, 1.9, 0.1, -0.9);
    let pv = price_rbergomi_call(&market, as_of, expiry, strike, 40_000);

    // 1Y ATM call, ~20% vol, contract size 100: roughly 7–9/share ⇒ 700–900.
    assert!(pv > 0.0, "rBergomi ATM call PV must be positive, got {pv}");
    assert_in_range(pv, 300.0, 1500.0, "rBergomi ATM call PV range");
}

/// As the vol-of-vol `η → 0` the rBergomi model collapses to Black-Scholes at
/// the surface lognormal volatility. The Monte Carlo ATM call price must
/// converge to the closed-form Black-Scholes price — a genuine, non-circular
/// analytic reference (no golden fixture).
#[test]
#[ignore = "slow: covered by mise rust-test-slow"]
fn rbergomi_small_eta_converges_to_black_scholes() {
    let as_of = date!(2024 - 01 - 01);
    let expiry = date!(2025 - 01 - 01);
    let spot = 100.0;
    let strike = 100.0;
    let vol = 0.20;

    // Near-zero vol-of-vol ⇒ deterministic variance ξ₀ = vol² ⇒ BS(vol).
    // ρ = 0 keeps the η→0 limit exactly Black-Scholes.
    let market = rbergomi_market(as_of, spot, vol, 0.0, 1e-3, 0.1, 0.0);
    let mc_price = price_rbergomi_call(&market, as_of, expiry, strike, 120_000);

    // The pricer day-counts the expiry on Act365F; 2024 is a leap year, so the
    // accrual is 366/365 years. Use the same maturity for the BS reference.
    let t = 366.0 / 365.0;
    let bs_price = black_scholes_spot_call(spot, strike, 0.0, 0.0, vol, t) * 100.0; // contract size 100

    let rel = (mc_price - bs_price).abs() / bs_price;
    assert!(
        rel < 3e-2,
        "η→0 rBergomi ATM call ({mc_price}) should converge to Black-Scholes \
         ({bs_price}); rel err {rel}"
    );
}

/// The rBergomi pricer is deterministic: pricing the same instrument twice
/// with the same seed yields a bit-identical PV (INVARIANTS §2).
#[test]
fn rbergomi_pricing_is_deterministic() {
    let as_of = date!(2024 - 01 - 01);
    let expiry = date!(2025 - 01 - 01);
    let spot = 100.0;
    let strike = 105.0;

    let market = rbergomi_market(as_of, spot, 0.22, 0.01, 1.5, 0.12, -0.7);
    let pv1 = price_rbergomi_call(&market, as_of, expiry, strike, 30_000);
    let pv2 = price_rbergomi_call(&market, as_of, expiry, strike, 30_000);

    assert_eq!(
        pv1.to_bits(),
        pv2.to_bits(),
        "rBergomi pricing must be bit-identical across runs: {pv1} vs {pv2}"
    );
}

/// A higher Hurst exponent (smoother variance paths) leaves the ATM price in
/// the same ballpark — a sanity guard that the RL Volterra generator handles
/// the full H ∈ (0, ½) range without blowing up.
#[test]
#[ignore = "slow: covered by mise rust-test-slow"]
fn rbergomi_atm_price_stable_across_hurst() {
    let as_of = date!(2024 - 01 - 01);
    let expiry = date!(2025 - 01 - 01);
    let spot = 100.0;
    let strike = 100.0;

    let mut prices = Vec::new();
    for &h in &[0.05, 0.10, 0.25, 0.45] {
        let market = rbergomi_market(as_of, spot, 0.20, 0.0, 1.2, h, -0.8);
        let pv = price_rbergomi_call(&market, as_of, expiry, strike, 40_000);
        assert!(pv > 0.0, "rBergomi ATM call must be positive for H={h}");
        prices.push(pv);
    }

    // ATM price is fairly insensitive to H at fixed η; all within a 2x band.
    let min = prices.iter().cloned().fold(f64::INFINITY, f64::min);
    let max = prices.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    assert!(
        max / min < 2.0,
        "rBergomi ATM price should be stable across H, got {prices:?}"
    );
}

/// Rough Bergomi MC must reject an in-window discrete dividend (ex-date
/// strictly after `as_of` and at/before expiry) because the escrowed-dividend
/// spot adjustment applied by `collect_inputs_extended` is a Black-Scholes-only
/// construct and is invalid under stochastic volatility.
///
/// This mirrors the identical guards in `heston_mc_pricer` and
/// `rough_heston_mc_pricer` (W-31).
#[test]
fn rbergomi_rejects_in_window_discrete_dividend() {
    let as_of = date!(2024 - 01 - 01);
    let expiry = date!(2025 - 01 - 01);
    // Ex-date strictly inside the option's life.
    let ex_date = date!(2024 - 06 - 15);

    let market = rbergomi_market(as_of, 100.0, 0.20, 0.0, 1.9, 0.1, -0.9);

    let mut call = create_call(as_of, expiry, 100.0);
    call.discrete_dividends = vec![(ex_date, 2.0)];
    call.pricing_overrides.model_config.mc_paths = Some(500);

    let registry = standard_registry();
    let result = registry.price_with_metrics(
        &call,
        ModelKey::MonteCarloRoughBergomi,
        &market,
        as_of,
        &[],
        PricingOptions::default(),
    );

    assert!(
        result.is_err(),
        "rBergomi MC must return Err for in-window discrete dividend, got Ok"
    );
    let msg = result.unwrap_err().to_string().to_lowercase();
    assert!(
        msg.contains("discrete dividend") || msg.contains("discrete_dividend"),
        "error message should mention discrete dividends, got: {msg}"
    );
}

/// Rough Bergomi MC must still price successfully when a discrete dividend's
/// ex-date is outside the option's life (already past or after expiry) — the
/// guard must not be over-broad.
#[test]
fn rbergomi_accepts_out_of_window_discrete_dividend() {
    let as_of = date!(2024 - 01 - 01);
    let expiry = date!(2025 - 01 - 01);
    // Ex-date is before `as_of` — outside the window, so no rejection.
    let ex_date_past = date!(2023 - 06 - 15);
    // Ex-date is after `expiry` — also outside the window.
    let ex_date_future = date!(2025 - 06 - 15);

    let market = rbergomi_market(as_of, 100.0, 0.20, 0.0, 1.9, 0.1, -0.9);

    let registry = standard_registry();

    // Past ex-date: should succeed.
    let mut call_past = create_call(as_of, expiry, 100.0);
    call_past.discrete_dividends = vec![(ex_date_past, 2.0)];
    call_past.pricing_overrides.model_config.mc_paths = Some(500);
    let result_past = registry.price_with_metrics(
        &call_past,
        ModelKey::MonteCarloRoughBergomi,
        &market,
        as_of,
        &[],
        PricingOptions::default(),
    );
    assert!(
        result_past.is_ok(),
        "rBergomi MC should succeed when ex-date is before as_of: {result_past:?}"
    );

    // Future ex-date (after expiry): should succeed.
    let mut call_future = create_call(as_of, expiry, 100.0);
    call_future.discrete_dividends = vec![(ex_date_future, 2.0)];
    call_future.pricing_overrides.model_config.mc_paths = Some(500);
    let result_future = registry.price_with_metrics(
        &call_future,
        ModelKey::MonteCarloRoughBergomi,
        &market,
        as_of,
        &[],
        PricingOptions::default(),
    );
    assert!(
        result_future.is_ok(),
        "rBergomi MC should succeed when ex-date is after expiry: {result_future:?}"
    );
}

/// The notional scales the rBergomi PV linearly.
#[test]
fn rbergomi_price_scales_with_notional() {
    let as_of = date!(2024 - 01 - 01);
    let expiry = date!(2025 - 01 - 01);
    let spot = 100.0;
    let strike = 100.0;

    let market = rbergomi_market(as_of, spot, 0.20, 0.0, 1.4, 0.1, -0.85);

    let mut call_100 = create_call(as_of, expiry, strike);
    call_100.notional = Money::new(100.0, Currency::USD);
    call_100.pricing_overrides.model_config.mc_paths = Some(30_000);

    let mut call_300 = create_call(as_of, expiry, strike);
    call_300.notional = Money::new(300.0, Currency::USD);
    call_300.pricing_overrides.model_config.mc_paths = Some(30_000);

    let registry = standard_registry();
    let pv_100 = registry
        .price_with_metrics(
            &call_100,
            ModelKey::MonteCarloRoughBergomi,
            &market,
            as_of,
            &[],
            PricingOptions::default(),
        )
        .expect("pricing should succeed")
        .value
        .amount();
    let pv_300 = registry
        .price_with_metrics(
            &call_300,
            ModelKey::MonteCarloRoughBergomi,
            &market,
            as_of,
            &[],
            PricingOptions::default(),
        )
        .expect("pricing should succeed")
        .value
        .amount();

    let rel = (pv_300 - 3.0 * pv_100).abs() / (3.0 * pv_100);
    assert!(
        rel < 1e-9,
        "rBergomi PV must scale linearly with notional: 3·{pv_100} vs {pv_300}"
    );
}
